### PR TITLE
New pick screen + Captains mode

### PR DESCRIPTION
**Pull request by ProstoSanja**
https://cdn.discordapp.com/attachments/261589235889471489/348883002513948674/unknown.png
image
This is pretty much it, almost ready.

### CODE REVIEW

**Comment by ProstoSanja** [comment]
image
image
i guess it is working, now only beautification remains

**Comment by chrisinajar** [comment]
have you gotten chat working yet?

**Comment by ProstoSanja** [comment]
no, chat is hardest of what remains, but i am working on it
we still have 2 weeks left
hope, ill do it in time

**Comment by warpdragon** [comment]
Illustrations are hopefully getting finished in the next couple of days.

**Comment by chrisinajar** [comment]
If you can get it done 1 week from today, we're in great shape.

**Comment by ProstoSanja** [comment]
okay, will try my best

**Pull request merged**
