### PR TITLE
Reflex items

### PR DESCRIPTION
**Pull request by Derk00**
These are the old reflex items but without reflex cores

### CODE REVIEW

**Comment by imaGecko** [comment]
doesn't return any errors on my local files

**Comment by imaGecko** [comment]
Tested the items, seem to work just fine.
Regen Crystal gives an error when upgraded while the active is still running

Cannot reproduce the travis error

**Comment by chrisinajar** [comment]
Once this is done we get to schedule the tournament :D

**Comment by imaGecko** [comment]
Did the nuking option of just copying everything over to a clean branch. Should be 100% exactly the same changes

**Comment by Derk00** [comment]
I see that it works now, but why would that fix it tho? You are copying everything, so if there were any errors, they are copied as well right?

**Pull request merged**
