### PR TITLE
remove tier 6 boses

### PR DESCRIPTION
**Pull request by srxzr**

### CODE REVIEW

**Comment by imaGecko** [comment]
is this going to be finished?

**Comment by srxzr** [comment]
I added all of the things in the issue, please let me know if anything is missing

**Comment by imaGecko** [comment]
Issues from first glance:

Tier 5 Charger
Pillar doesn't need a t5 version
Charge Ability doesn't have a t5 version

Lycan
missing t5 damaging and spawning abilities

Ogre
missing t5 damaging abilities
(i am also gonna guess ogre is going to spawn with the t3 small ogres)

Spider Boss
missing t5 damaging and spawning abilities
Spider Summons missing their respective t5 damaging abilities (the green disarming ball for example)

Temple Guardian
gonna make a guess that the t5 spawner currently spawns t4 guardians

Twins
Does the main twin actually spawn the t5 dumb twin?

A bunch of unnecessary files
npc_dota_boss_tier_2_tier5
npc_dota_boss_tier_3_tier5
npc_dota_boss_tier_4_tier5
npc_dota_boss_tier_5_tier5

**Comment by srxzr** [comment]
Yes I will finish it today my time, sorry for the delay

**Comment by srxzr** [comment]
Missing files added sorry for delay tell me if anything is still missing.

**Comment by l34Um1** [comment]
Ready to merge. I'll need your paypal so I can pay you once it's been merged. I also need to be notified when this has been merged because numbers need to be done on this asap.

**Pull request merged**
