### PR TITLE
Cave Update

### PR DESCRIPTION
**Pull request by warpdragon**
paths from cave to map. changes to cave.lua to support cave side-doors.

### CODE REVIEW

**Comment by warpdragon** [comment]
any progress on the coding end today-ish?

**Comment by Chronophylos** [comment]
my repo is broken i need to link the files again

**Comment by warpdragon** [comment]
This map is physically ready, but functionally broken. Help would be very much appreciated.

**Comment by warpdragon** [comment]
https://youtu.be/1Isjgc0oX0s

**Comment by warpdragon** [comment]
Can someone look at why this is bugging out? Neither of us can figure it out... @SquawkyArctangent ?

**Pull request closed without merging**
