### PR TITLE
Doors and fancy stuff

### PR DESCRIPTION
**Pull request by warpdragon**
added doors. doors need lua to make them function. doors are no-clip. added fancy shit to tier 1 boss pits.
Doors are:
rad_door_1, rad_door_2, rad_door_3
dire_door_1, dire_door_2, dire_door_3

### CODE REVIEW

**Comment by warpdragon** [comment]
image

**Comment by warpdragon** [comment]
image

**Comment by warpdragon** [comment]
image

**Comment by Chronophylos** [comment]
I'm working on something to open and close these doors.

**Comment by warpdragon** [comment]
Done

**Comment by Chronophylos** [comment]
I approve

**Pull request merged**
