### PR TITLE
Clone Location

### PR DESCRIPTION
**Pull request by IbraheemTuffaha**
Added a line explaining where to choose the location file for the local clone.

### CODE REVIEW

**Comment by warpdragon** [comment]
there's something wrong with this PR i can't seem to find it, though.

**Comment by Trildar** [comment]
Looks like various hero KVs not matching vanilla DotA. Unrelated to this PR.

What did Valve do now?

**Comment by IbraheemTuffaha** [comment]
I'm kind of new here, not sure what I did wrong!
It's just an edit on one doc, adding one line!!

**Comment by warpdragon** [comment]
U didnt do anything wrong. As for what u do now im not sure. Just wait and see. Thanks for the update btw. Docs are so important. Did u have any trouble using them besides that?

**Comment by IbraheemTuffaha** [comment]
They were actually very helpful for the installation process, I finished installation and ran the map from the Dota 2 Tools and works just fine.
After that, as for contribution, the files say check out discord, I did and there's nothing new there!
Am I missing something here?
Now I wanna know what can I do to help here. @warpdragon

**Pull request closed without merging**
