### PR TITLE
Lycan Boss Changes (Mainly Tier 5)

### PR DESCRIPTION
**Pull request by POCKETMONEY99**
The first changes affects both tier 3 and tier 5 lycan boss. 
Reduced Shapeshift duration to 60 seconds. This doesn't affect the boss fight, however if for any reason you leave the boss pit the boss will reset. Currently it can become full HP and have wolf form if it is allowed to reset. 

Removed Lcyans mana costs. He will now always shapeshift at 50% HP

Tier 5 lycan boss is hilariously OP, but its spawn rate is low. Nerfed it to the point where it is reasonably strong. 

Nerfed claw attack damage from 25000 (LMAO) to 9000 (this is now simillar to ogre tank boss)
Nerfed claw lunge damage from 20000 to 8000
Nerfed rupture ball speed to 700 (same as tier 3 boss.)

### CODE REVIEW

**Comment by TheUnholyWrath** [comment]
does shapeshift still need a manacost?

**Comment by DarkoniusXNG** [comment]
Don't nerf the damage on rupture ball.

**Comment by DarkoniusXNG** [comment]
Nerf on rupture ball speed was fine. I just said damage.

**Comment by DarkoniusXNG** [comment]
Nvm, I am blind.

**Pull request closed without merging**
