### PR TITLE
Azazel Purchasables - Elixiers

### PR DESCRIPTION
**Pull request by fcalife**
Includes suggested visuals, tooltips, and some placeholder icons.

#2110

### CODE REVIEW

**Comment by fcalife** [comment]
This PR also includes the #2111 implementation.

**Comment by l34Um1** [comment]
I don't know how to test this. I keep trying but I just can't seem to be able to get access to the items ingame. Are they added to the shop/cheat list? I know Azazel isn't in yet but for now these should just be in the normal shop then. How are you testing them ingame?

**Comment by fcalife** [comment]
I test this by giving my hero the items with

-item item_elixier_burst_3,
-item item_elixier_hybrid_4,
etc.

**Comment by l34Um1** [comment]
This seems to all be in order, except it's missing tooltips when I test it.

**Comment by fcalife** [comment]
The tooltips are in separate files which aren't integrated in the main tooltip file when testing, but will be the next time this PR is merged and the game is "built".

In order to test them, you can temporarily copy-paste them into the addon_english.txt tooltip file.

These are the relevant files:
* game/resource/English/ability/items/tooltip_azazel_summons.txt
* game/resource/English/ability/items/tooltip_elixiers.txt
* game/resource/English/modifier/items/modifier_elixiers.txt
* game/resource/English/npc/npc_creeps.txt

**Comment by carlosrpg** [comment]
please fix the errors found on Travis. If you need any help ask us on discord

**Comment by fcalife** [comment]
The only failing checks remaining are a missing tooltip for a hidden modifier (lol) and an item upgrade path error that is, AFAIK, intended for those new items (since they don't belong in the regular shop normally).

**Comment by carlosrpg** [comment]
@l34Um1 do the items should be able to be bought using higher cores? I think that is what travis is complaining

**Comment by l34Um1** [comment]
No, but I also don't see it as a big harm. But it's not supposed to be possible.

**Comment by chrisinajar** [comment]
Read through all the errors, some of them are ID number collisions and the very last couple lines is the missing tooltip. I'll fix the reverse compatibility errors, don't worry about those.

**Comment by fcalife** [comment]
travis seems to be stuck on another problem (?), please advise 😕

**Comment by carlosrpg** [comment]
Dude, it was working and passing the tests, why did you had to change?

**Comment by fcalife** [comment]
I was doing stuff locally and pushed without looking what you did. Then I noticed it and reverted the two commits I did. Isn't that enough?

**Comment by carlosrpg** [comment]
I force updated to the commit that was working, this will make into the game next release

**Pull request merged**
