### PR TITLE
Fix droppable aghanim

### PR DESCRIPTION
**Pull request by ProstoSanja**
Applied undroppable tag to all 5 of them
Fix for OpenAngelArena/Bug-Reports#57

### CODE REVIEW

**Comment by Haganeko** [comment]
That will make aghs undroppable on all heroes... It should at least have a tooltip change to say so.

**Comment by Chronophylos** [comment]
And color it

**Comment by ProstoSanja** [comment]
quick suggestion how to do it? (I last toched dota dev in may)

**Comment by Chronophylos** [comment]
Take a look at [this](https://github.com/OpenAngelArena/oaa/blob/7c162fe7912ccd5f768e5d04907f020d6393f57b/game/resource/English/ability/units/tooltip_lich_dark_ritual.txt#L5). You can essentially use HTML. I think dota doesn't like the `color=orange` so you need to do `color=#FFA500`.

**Comment by ProstoSanja** [comment]
So you wantme to color part which says it is undroppable?
am i correct?

**Comment by Chronophylos** [comment]
Yeah. We want to mark any changes to vanilla. Like Lich's Ritual can target neutrals and Dark Seer's Ion Shell cannot target creeps.

**Comment by ProstoSanja** [comment]
`color=#FFA500` still didnt work

**Comment by Chronophylos** [comment]
Did you rebuild the localization?
`node run scripts/generate-translations.js` 
It gives a error but the files are sill parsed correctly

**Comment by ProstoSanja** [comment]
yes, text appears, but still no orange color

**Comment by Chronophylos** [comment]
Hm
Dota is stupid
Also checkout Travis I don't think you have seen i yet

**Comment by ProstoSanja** [comment]
Yeah, I already dealt with it, had stupid mistake there

**Comment by ProstoSanja** [comment]
i dont understand one thing.... i pushed commit to fix travis, but it didnt get here in pull....
https://github.com/ProstoSanja/oaa/commit/62275a2432fd8bc641f1c5c303abbacb44021b6f

**Comment by Chronophylos** [comment]
That is really weird.

**Comment by ProstoSanja** [comment]
Will finish tomorrow morning

**Comment by ProstoSanja** [comment]
image

**Pull request merged**
