### PR TITLE
razor buff

### PR DESCRIPTION
**Pull request by lovesmuffins**

### CODE REVIEW

**Comment by lovesmuffins** [comment]
im retarded and pushed razor buffs with former buffs, hope it doesn't make any difference.

**Comment by Larenall** [comment]
What is the point of buffing a hero that did well on the tournament?

**Comment by POCKETMONEY99** [comment]
> 
> 
> What is the point of buffing a hero that did well on the tournament?
Razor should recieve a buff to static link as the actual drain effect isn't as oppressive as it should be at from levels 1 to 4. This is because people get alot more damage items more quickly in OAA then in dota. 

While these buffs are likely too much much he should get a static link buff at dota levels.

**Comment by Larenall** [comment]
I cant say i agree on that. Damage drain is good as it is now. Around lvl 20 ur carry is usually 6 slotted - satanic, bkb, mkb, daedalus,butterfly. + boots. At that stage ur items are usually lvl 2 and they arent that much different in terms of stats. When the differece between lvl1 and lvl3 items your carry is around lvl 28 and at that point razor has lvl5 link which is enough dmg drain at that stage. Also u have to remember that he has a great bossing potential cuz he can use it on bosses and buy buffing him like that u allow for even faster boss killing than it is now. Having +400 dmg on bosses so early on is crazy. We saw on the tournament how fast he can wipe out bosses, imagine doing it even faster

**Comment by Larenall** [comment]
> > What is the point of buffing a hero that did well on the tournament?
> > Razor should recieve a buff to static link as the actual drain effect isn't as oppressive as it should be at from levels 1 to 4. This is because people get alot more damage items more quickly in OAA then in dota.
> 
> While these buffs are likely too much much he should get a static link buff at dota levels.

I cant say i agree on that. Damage drain is good as it is now. Around lvl 20 ur carry is usually 6 slotted - satanic, bkb, mkb, daedalus,butterfly. + boots. At that stage ur items are usually lvl 2 and they arent that much different in terms of stats. When the differece between lvl1 and lvl3 items your carry is around lvl 28 and at that point razor has lvl5 link which is enough dmg drain at that stage. Also u have to remember that he has a great bossing potential cuz he can use it on bosses and buy buffing him like that u allow for even faster boss killing than it is now. Having +400 dmg on bosses so early on is crazy. We saw on the tournament how fast he can wipe out bosses, imagine doing it even faster

**Comment by DarkoniusXNG** [comment]
@lovesmuffins I told you to close this PR. Multiple reasons why: 
1) You didn't create a new branch with a **different name**. Same name resulted in updating of old branch...
2) You are buffing a hero that is viable.
3) You are buffing talents, and I told you to leave talents to me until I refactor them.

**Comment by lovesmuffins** [comment]
dark hates me

**Pull request closed without merging**
