### PR TITLE
Add new hero, Takuan the Sōhei

### PR DESCRIPTION
**Pull request by RodneyMcKay**
- Missing tooltips
- Picking Screen icon is not being precached for reasons
- error with Troll Warlord somehow not detected in npc_heroes.txt (valve file)

### CODE REVIEW

**Comment by l34Um1** [comment]
Q: Dash: Consumes a charge to quickly dash 300 units in the direction you are facing, granting invincibility for the duration of the dash. Can be used to dash over cliffs and through trees.

Charges: 2 / 3 / 4 / 5 / 6 / 7
Charge Cooldown: 8s
Mana Cost: 50
_Dash Speed: 900_
Active ability

W: Guard: Hard dispels you. Reflects all projectiles that would hit you for the next 2 seconds. Can be used while stunned but consumes 2 charges of Dash if used while stunned.

_Can be activated while stunned but not while silenced._ 

Cooldown: 30 / 25 / 20 / 15 / 10 / 5
Reflect duration: 2
Mana Cost: 80
Active ability

E: Momentum: After moving 300 units your next attack is a critical strike and pushes your target 300 units. If you push the enemy into a cliff, tree or enemy hero they get slowed. Scales in crit damage, slow amount and duration. 

Movement required to trigger: 300
Push distance: 300
Crit multiplier: 1.25 / 1.5 / 1.75 / 2
Movement Slow : 15 / 20 / 25 / 30 / 35 / 45%
Slow Duration: 1.5 / 2 / 2.5 / 3 / 3.5 / 4.5 
_Push speed: 900_ 
Passive ability

R: Flurry Of Blows: Active. Sohei becomes invulnerable, randomly attacking all targets in the AOE, one at a time with the intention of pushing them back into the AOE. Each hit triggers Momentum. Ends after either the duration or the maximum amount of attacks have run out. Can be reactivated to cancel.

AOE: 400
Number of Attacks: 5 / 10 / 15 / 20 / 25
Interval between attacks: 0.4s
Duration: 5 / 6 / 7 / 8 / 9
Mana Cost: 150
Cooldown: 100s
_Cast Point: 1_
Active ability


_This goes into green alt text_

**Comment by warpdragon** [comment]
gonna edit this portrait up real quick

**Comment by warpdragon** [comment]
Sohei_portrait

**Comment by warpdragon** [comment]
preview 1

**Comment by warpdragon** [comment]
preview

**Comment by chrisinajar** [comment]
warp, add the vinget

**Comment by warpdragon** [comment]
@chrisinajar i already PRd my portrait to Cookies. What did you mean by vignette?

**Comment by warpdragon** [comment]
NEVERMIND i know what u mean 1 sec

**Comment by carlosrpg** [comment]
We need to reduce his range. He is almost ranged melee right now

**Comment by warpdragon** [comment]
Vignette done.

**Comment by warpdragon** [comment]
dat guard cd tho POGGERS

**Comment by Trildar** [comment]
Guard description isn't entirely accurate I think. Since what it really does is reflects all targeted spells and ranged attacks.

**Comment by chrisinajar** [comment]
Anyone know how the momentum collision stun is supposed to work?

**Comment by warpdragon** [comment]
Last i heard, if the target hits a wall or other obstruction it is slowed or stunned i don't remember which.

**Comment by Melongod** [comment]
If the unit that was knocked back is knocked into anything, it seems like both the unit that was knocked back and the unit that it was knocked into (I think, it's kinda ambiguous) is slowed. If the stun talent is taken then they get stunned.

**Comment by l34Um1** [comment]
Momentum collision: If knocked into a tree or cliff slow the attacked hero. If knocked into an enemy hero slow both heroes. 
With the talent: apply a .2 second stun when the collision happens. The slow still occurs.

**Comment by fcalife** [comment]
@chrisinajar the method i imagined consists of three checks every tick of the knockback movement:

https://i.imgur.com/tAFbE7f.png

Imagine S is sohei, X is the enemy being knocked back, the arrow indicates the direction of movement.

1. Check for collision with enemy heroes in the red circle (64 radius, usual hero collision size), if yes, this is a hero collision;
2. Check if there are any trees in the green circle (80 radius, bit larger than usual collision size), if yes, this is a tree collision;
3. Check if any of the three blue markers is at a superior elevation compared to the knockbacked unit, if yes, consider this a cliff collision;

I assume hero collisions shouldn't stop the knockback, but tree/cliff collisions should. Trees should also be destroyed when collided with.

I'll implement this later today if able, best regards!

**Comment by Melongod** [comment]
Change the "AFFECTS:" part of the FLURRY OF BLOWS tooltip from "Enemy Units" to "Enemy Heroes".
Change the wording of the MOMENTUM ability description where it says "they get slowed" to "they both get slowed".

**Comment by chrisinajar** [comment]
I just checked if the spot isn't traversable. It'll make people stake the stun when they go down-hill but meh....

**Pull request merged**
