### PR TITLE
Urn of Sorcery

### PR DESCRIPTION
**Pull request by VilkkuV**
#121

### CODE REVIEW

**Comment by imaGecko** [comment]
looks like you missed a squiggly somewhere

**Comment by VilkkuV** [comment]
What is next available ItemID?

**Comment by warpdragon** [comment]
I think u run kv-lib in node-js

**Comment by warpdragon** [comment]
Incidentally the icon for this is in models discussion from like a month ago

**Comment by warpdragon** [comment]
I sent you a pull request @VilkkuV

**Comment by VilkkuV** [comment]
Now it's ready for review.

**Comment by chrisinajar** [comment]
Will test locally and fix any problems I find

**Pull request merged**
