### PR TITLE
Map Visual Update

### PR DESCRIPTION
**Pull request by warpdragon**
The map is getting kind of stale, and there's a world of cool things to explore with new decorative strategies. It's less about making the map "look cool" and more just exploring what Hammer is actually capable of which, for those of you who play custom games alot know, is quite a lot!

### CODE REVIEW

**Comment by warpdragon** [comment]
image

**Comment by warpdragon** [comment]
image

**Comment by warpdragon** [comment]
https://youtu.be/teOUlpf_U8s

**Comment by warpdragon** [comment]
By the way I'm gonna be gone all day. I'm labeling this "Work in progress" because I wish to do more. This being the case: please don't edit the map before merging this.

**Comment by allanvbhg** [comment]
I love those stairs!

**Comment by allanvbhg** [comment]
Soo original

**Comment by chrisinajar** [comment]
Can you show what the stairs look like in game? They may need a better texture before merging depending on how they appear in the engine.

Great work! :+1:

**Comment by warpdragon** [comment]
I removed some of those stairs. it's juts one instead of two in those locations i illustrated. also it looks pretty good.
stairs

**Comment by warpdragon** [comment]
actually wait a minute...now that you mention it it looks super shitty. wtf? i could override the vmat...

**Comment by warpdragon** [comment]
ok i'm playing in the game with it now. it looks fine. even on lowest settings.

**Comment by warpdragon** [comment]
I'm a motherfuckin Stair Boy

**Comment by warpdragon** [comment]
ok i'm done for now. somehow fucked up my branch and this is a decent stopping point. map works. looks great. enjoy!

**Comment by warpdragon** [comment]
Im gonna close this and make a new pr. Somehow fucked up the branch but im gonna move the uh... the boss pits closer

**Pull request closed without merging**
