### PR TITLE
MIDAS

### PR DESCRIPTION
**Pull request by DarkoniusXNG**
1) Remove Hand of Midas upgrades because they are innefficient/bait items.
2) Hand of Midas level 1 changes:
* Increased bonus attack speed from 40 to 50.
* Increased xp multiplier from 2 to 3.
* Increased bonus gold from 150 to 160. (Reminder: when you use OAA Midas you get creep's normal bounty too).
* Recipe cost increased from 1500 to 1750.

### CODE REVIEW

**Comment by lovesmuffins** [comment]
nobody asked you to do this

**Comment by lovesmuffins** [comment]
stop baiting chris

**Comment by DarkoniusXNG** [comment]
Its a funny meme though.

**Comment by lovesmuffins** [comment]
> Its a funny meme though.

I worked way too much on my changes for u to meme me. Cmon bruh. If chris wants to put my changes in, let him. If he doesn't and closes it than you can put these back up and you win ok?

**Pull request closed without merging**
