### PR TITLE
Fix roshlings (I hope)

### PR DESCRIPTION
**Pull request by Haganeko**
Got rid of inherent roshan buffs from cave roshlings. Hope it'll fix them.

### CODE REVIEW

**Comment by Trildar** [comment]
You'll also want to remove Devotion if you don't want them to have vanilla Roshan scaling armour bonus. Possibly some other scaling tied to that as well. Not too sure.
Also, you probably want to change the AttackRate, unless you actually want them to have 1 attack every 2 seconds, because the inherent buffs gives them attack speed such that they will have 1 attack per second.

**Comment by Haganeko** [comment]
Oh. Can we give them a passive which grants attack speed, so they won't be super vulnerable to slows?

**Comment by chrisinajar** [comment]
Giving them a passive to increase attack speed seems silly compared to just making them attack faster. We could also do some responsive modifier that gives attack speed based on minus attack speed (like a % resistance to attack speed slow) but that's another-PR-work for future chris

**Comment by Haganeko** [comment]
Increasing base attack speed will make them vulnerable to slows. Creating a whole attack slow resistance is way more complicated than just giving them AS

**Pull request merged**
