### PR TITLE
Initial runthrough of talent changes

### PR DESCRIPTION
**Pull request by spar36**
WIP

Issue #475

### CODE REVIEW

**Comment by spar36** [comment]
Here is the link to a spreadsheet that says what is done.
All of the "add" heroes can be done, just will take time to put them in by hand.
All "special" heroes will require an ability to be created.

https://docs.google.com/spreadsheets/d/1l7yKkpZlyLGWE-gyBBwEjGVK8InvrezDPFy8UPXfisk/edit?usp=sharing

**Comment by Haganeko** [comment]
Ursa was an April fools joke which I'm starting to regret.

**Comment by spar36** [comment]
No, we will still put it in.

**Comment by spar36** [comment]
If stream happens tomorrow (4/9), merge this in. It is all the talents I could easily do so far.

**Pull request merged**
