### PR TITLE
Include Bots for testing purposes

### PR DESCRIPTION
**Pull request by RamonNZ**
I've had this basic OAA farming/fighting bot for 2-3 weeks now. I was asked if I could upload it for the purpose of helping test games.

Instructions are included in the readme.md.

I haven't updated it much since I made it, so in practice they do strange things during duelling, or knowing when a camp has been buffed beyond their ability to fight it, and obviously they don't do bosses.

The settings.lua has previously been changed so that they can be used right away.

### CODE REVIEW

**Comment by Chronophylos** [comment]
Move the readme.md to /docs/

**Comment by RamonNZ** [comment]
Done.

**Comment by chrisinajar** [comment]
This is pretty awesome! I'd love to see someone automate those commands to a boolean flag in `settings.lua`, but there's no side effects of merging this in like this, and I bet the QA guys will *love* it.

Thanks!

**Comment by warpdragon** [comment]
TY!

**Pull request merged**
