### PR TITLE
Map Update

### PR DESCRIPTION
**Pull request by warpdragon**
map update. created backdoor to first tier 1. moved boss pits closer to spawn. updated visual elements. added particles to center of the map.

### CODE REVIEW

**Comment by warpdragon** [comment]
Ok i'm done. Not sure what's wrong with my git. But it's a pretty dope update.

**Comment by warpdragon** [comment]
image

**Comment by warpdragon** [comment]
image

**Comment by warpdragon** [comment]
image

**Comment by warpdragon** [comment]
image

**Comment by warpdragon** [comment]
image

**Comment by warpdragon** [comment]
Oh yeah! I forgot. New Dire themed Duel Arena: 
image

**Comment by warpdragon** [comment]
image

**Comment by warpdragon** [comment]
Some cool cave themed deco image

**Comment by allanvbhg** [comment]
Blonk bleckers 🤔

**Comment by allanvbhg** [comment]
Looks neat, but might need to add the duel zone

**Comment by allanvbhg** [comment]
Can I give that a try?

**Comment by warpdragon** [comment]
what does "add the duel zone" mean?

**Comment by allanvbhg** [comment]
Edit* the duel zone

**Comment by allanvbhg** [comment]
Just remove the blinker blonckers

**Comment by warpdragon** [comment]
Done. Have a tour: https://youtu.be/J_0sHbs1byg

**Comment by warpdragon** [comment]
U cant remove blurp bloopers!

**Comment by warpdragon** [comment]
Its all wrapped up

**Comment by Trildar** [comment]
Is the Fountain area trigger also adjusted in this?

**Comment by Haganeko** [comment]
Does this fix #1174?

**Comment by warpdragon** [comment]
Nope. The problem was never brought to my attention any of the 5 times i asked for input on the map. Im sure those are important issues i just didnt. lul. Also i just woke up.

**Comment by warpdragon** [comment]
Fixed https://cdn.discordapp.com/attachments/268846873643581442/328561089660977152/DireFountain.gif

**Comment by Haganeko** [comment]
I assume people can't stand on the leftover cliff by cutting trees?

**Comment by warpdragon** [comment]
blink blocker prevents them from getting behind the fountain. they'd have to walk thru the fountain to get on that cliff behind.

**Pull request merged**
