### PR TITLE
Fix Greaves Sidegrade

### PR DESCRIPTION
**Pull request by Haganeko**
I was told it was decided on a Town Hall that all side grade costs should be the same as vanilla; this should fix that.

### CODE REVIEW

**Comment by warpdragon** [comment]
According to Travis:
✖ there are no missing tooltips
shouldn't that say "there are missing tooltips", Chris?

**Comment by Haganeko** [comment]
It's failing the "don't have missing tooltips" check

**Comment by warpdragon** [comment]
Basically, because the name "item_greater_guardian_greaves_dummy.txt" doesn't follow the <item_name_level> pattern as regular GGG, it needs its own tooltip file - I think.

**Comment by Haganeko** [comment]
Thank you for the assistance... way ahead of you, though.

**Comment by warpdragon** [comment]
✖ can run parse script [pass: 0, fail: 1, duration: 89ms]

no idea about that one, friend.

**Comment by Haganeko** [comment]
Found it missing "

**Comment by warpdragon** [comment]
oh i see. parse means "syntax bonkered" got it

**Comment by warpdragon** [comment]
All checks have passed
1 successful check
HELL YES

**Pull request merged**
