### PR TITLE
Shrines

### PR DESCRIPTION
**Pull request by warpdragon**
Now with shrines!

Note:
Shrines are named the following: ```<dire/radiant>_shrine_<top/bot>``` they are invulnerable at start and have invulnerability count = 1. Set to 0 for them to be vulnerable.

### CODE REVIEW

**Comment by chrisinajar** [comment]
they just work?.. wow

**Comment by warpdragon** [comment]
i didn't check. they will work. if they don't then hey, atleast they probably won't break the game.

**Comment by warpdragon** [comment]
i'll check it in a minute

**Comment by warpdragon** [comment]
yup. they work! rebasing...

**Comment by warpdragon** [comment]
see?

**Comment by warpdragon** [comment]
rebased and it still fails. But the shrines work 100% as expected.

**Comment by chrisinajar** [comment]
WAY TO COPY IT OVER TO CAPTAINS MODE FILE WARP JEEZ YOU HAD ONE JOB GET IT TOGETHER

jk thanks homie <3

**Pull request merged**
