### PR TITLE
Added Bosses from EBF

### PR DESCRIPTION
**Pull request by Chronophylos**
From #1281 
####  Progress
+ [x] Automata Factory
+ [x] Dire beast
+ [x] Nyx Slayer
+ [x] Hell Golem
+ [x] Death Archdemon
+ [x] Doom, Demon King  
+ [x] Asura, God of Demons

If have adjusted the Bosses to (hopefully) work in OAA. This excludes balance.
If you want any balance changes to them later or tell me.

I copied the code from EBF and only did small changes to make the Bosses work.
Tooltips are generated too, but only in the english version

### CODE REVIEW

**Comment by Chronophylos** [comment]
Lots of stuff todo:
Bosses run around and attack everything
Console gets spammed with stuff the AI made and other things

**Comment by Chronophylos** [comment]
Also Creature Fire Breath is from Siltbreaker and somehow works without a BaseClass

**Comment by chrisinajar** [comment]
Not sure why the abilities don't cast, been fiddling with this locally.

**Comment by chrisinajar** [comment]
They're not even in the boss spawn list, and if you add them they don't work. This is still very much a WIP.

**Comment by chrisinajar** [comment]
automaton tier 2, Death Archdemon tier 3, hell golem tier 3, nyx slayer tier 3, demon king tier 4, god of demons tier 4

**Comment by chrisinajar** [comment]
this was the problem:
```
    "UseNeutralCreepBehavior"   "1"
```

**Comment by Haganeko** [comment]
So they work now?

**Comment by chrisinajar** [comment]
one does, DA next

**Comment by Haganeko** [comment]
There's a typo on Elder Dragon Form where it calls "Draconic Rage" as "Dragonic Rage".
"Dragonic" is not a word.

**Comment by Chronophylos** [comment]
Where?

**Comment by Haganeko** [comment]
Second to last word of the Description line

**Pull request closed without merging**
