### PR TITLE
WIND buffs and talent reshuffle

### PR DESCRIPTION
**Pull request by lovesmuffins**

### CODE REVIEW

**Comment by DarkoniusXNG** [comment]
It would be easier to review if you tell me what is each talent.

**Comment by TheUnholyWrath** [comment]
25 New Crit - Undispellable Windrun
20 Focus fire 20s - Windrun grants invisibility
15 Shackleshot Duration - Powershot Damage
10 Shackleshot Cooldown - 20 Damage 

@DarkoniusXNG

**Comment by DarkoniusXNG** [comment]
special_bonus_unique_windranger_2 (Focus Fire Kills Advance Cooldown by 20s.) still seems like garbage to me. I see this talent: special_bonus_unique_windranger_5  -> +2 Shackleshot Target talent seems interesting. Can you test if it works?

**Comment by lovesmuffins** [comment]
> special_bonus_unique_windranger_2 (Focus Fire Kills Advance Cooldown by 20s.) still seems like garbage to me. I see this talent: special_bonus_unique_windranger_5 -> +2 Shackleshot Target talent seems interesting. Can you test if it works?

works but seems a lot better in paper than testing. I'm going to swap it with the crit talent however.

**Comment by DarkoniusXNG** [comment]
Merged into #3278

**Pull request closed without merging**
