### PR TITLE
Mirana piercing arrow talent

### PR DESCRIPTION
**Pull request by AbitTheGray**
For #2160 

Still require testing (and minor code to write) but looks working in general.

Do not know why `npc_heroes_custom.txt` is having "problem" (huge amount of changes on GIT) with 1 new line.

Left all arrow-related talents in their original form. Even allow more-then-two added multishot arrows to be set in the other lvl 25 talent.

TODO
- [X] Kill creeps (not ancient creeps or hero or creep-hero (considered-hero)) on hit `target:ForceKill(reincarnation=false)`
- [X] Verify hitting but not affecting spell-immune units
- [X] Keep vision on target point for 3s instead of (currently) duration of the stun
- [X] Verify that multishot cannot hit same target
- [X] Verify arrow cannot hit invulnerable units
- [X] Change to first apply damage, then debuff
- [X] Start arrow `51` units in front of caster (change current value to be loaded from `AbilitySpecial`)
- [X] Verify travel speed of `857`
- **UNABLE** Fix ability to be displayed on picking screen (not a problem because it is same ability but...), not a bug but feature!
  - Can be solved by modifying picking screen

Personal note: Replace this new talent with talent that allows the arrow to pass through targets triggering on all of them. Seems more fitting for level 25.

### CODE REVIEW

**Comment by chrisinajar** [comment]
it's just because you saved the file with an editorconfig active, the npc custom thingy

**Comment by AbitTheGray** [comment]
Same as the Clinkz from #2344 this ability does not appear on hero picking screen instead the old (original) one.
Not tested translation, cannot get it working.

**Comment by AbitTheGray** [comment]
Added sounds on both cast and impact.
[Fly sound](https://dota2.gamepedia.com/Mirana/Sounds#Sacred_Arrow) is not used in Dota.

**Not tested (yet).
Will test ASAP.**
Should work anyway.

**Comment by chrisinajar** [comment]
does it have double cast to throw backwards?

**Comment by AbitTheGray** [comment]
**Not tested** - will test tomorrow after work.

Number of pierces is defined in `mirana_talents.txt` file in `game/scripts/npc/abilities/`.
The amount of pierces can be (but currently is not) referenced by tooltips using `arrow_pierce_count` (not tested).

Also replaced the Global Arrow with this near Pierce Arrow (with no translation - I am going into bed 23:54 here).

**Comment by AbitTheGray** [comment]
**WIP** of 2nd talent - Arrow Piercing Units.
Gonna find a way to modify Arrow's ExtraData or recast the arrow on every hit with decreased hit count by 1.

**Comment by AbitTheGray** [comment]
I though I had it fixed but just tested it and it goes through all units.

Will take a look at it tomorrow (sadly I only got time today to verify Kunkka's Tidebringer).

**Comment by AbitTheGray** [comment]
@chrisinajar Now I am happy with the current state.

The targeting cursor snaps to enemy unit and aggro creeps but I do not consider it a bug but how unit-target abilities work (which is required for self-cast, your way did not allow casting with cursor over the unit).

**Comment by chrisinajar** [comment]
You need to reject those other targets in a unit cast filter, it prevents it from even highlightning them. I got that working in my upgradable ward stack item.

**Pull request merged**
