### PR TITLE
Lock out enemy heroes from tier 1 bosses

### PR DESCRIPTION
**Pull request by chrisinajar**

### CODE REVIEW

**Comment by chrisinajar** [comment]
Partially closes #452, should really give rewards / unlock regardless of who kills

**Comment by Minnakht** [comment]
Rewards regardless of killer is a solution I'd be more in favor of as well if it was up to discussion at this point

**Comment by chrisinajar** [comment]
We need both.

**Comment by chrisinajar** [comment]
We have both!

**Pull request merged**
