### PR TITLE
Capture Points

### PR DESCRIPTION
**Pull request by M-Faraday**
Capture Points Finished

### CODE REVIEW

**Comment by M-Faraday** [comment]
The capture points were made for the oaa.test map

**Comment by l34Um1** [comment]
I tested this locally and the capture points don't show up for me and aren't pinged out on the minimap. Frankly none of it works. How would you recommend I test it to get the capture points to show up?

**Comment by Haganeko** [comment]
Perhaps stuff needs to be compiled?

**Comment by M-Faraday** [comment]
It was made for the test map. I also added a command to start capture points manually -capture I believe

**Pull request merged**
