### PR TITLE
First gold rework

### PR DESCRIPTION
**Pull request by Haganeko**
Baumi asked for less gold early.
Reduced early, increased past forty minutes.
Will need to be changed later when we introduce increasing creeps.

### CODE REVIEW

**Comment by Haganeko** [comment]
Incorporated #1167 by mistake. Should I close that one?

**Comment by warpdragon** [comment]
Rip gold

**Comment by Haganeko** [comment]
Changed the whole thing. Pray I don't alter it any further.

**Comment by Haganeko** [comment]
FYI models for total available gold are:
Original: 195n² + 585n
New: 23/9 n³ + 125/3 n² + 20950/9 n
By start of minute n. Just in case someone wants to plot and compare.

**Comment by chrisinajar** [comment]
Why nerf black dragon xp?

**Comment by Haganeko** [comment]
Me being stupid. Will fix. Thanks for spotting it.

**Pull request merged**
