### PR TITLE
Swap farming abilities of arcane/ggg and travels

### PR DESCRIPTION
**Pull request by chrisinajar**
Also made test cases run in windows / crappy nix envs

### CODE REVIEW

**Comment by Haganeko** [comment]
When was this decided?

**Comment by Chronophylos** [comment]
During a Townhall meeting i think

**Comment by Minnakht** [comment]
@Haganeko I think I recall Baumi saying something to that effect this week, not entirely sure though. 

I'm not sure if I'm entirely happy with this change, but I guess I can be

**Comment by imaGecko** [comment]
I think this makes much more sense, get ggg for fighting and stay back with tps and farm until you can tp in

**Comment by Haganeko** [comment]
The new TP boots tooltip doesn't include a description of Commensalism?

**Pull request merged**
