### PR TITLE
[WIP] Arcane boots rework

### PR DESCRIPTION
**Pull request by emperorgustaviiadolf**
Edited KV file for Greater Arcane Boots, added (not working) code for ticking GPM to LUA, fixed tooltip for greater arcane boots, started working on hotbar icon to display current percent of gold earned.

### CODE REVIEW

**Comment by Haganeko** [comment]
You have a change to package-lock.json, for some reason.

**Comment by Trildar** [comment]
Version number change. That file sometimes doesn't get updated when Chris does releases for some reason, which causes Node to want to update the files to match.

**Comment by Trildar** [comment]
This seems to be based on an old version though. Current version is already 3.1.0.
Please do a rebase or merge with the latest version.

**Comment by Trildar** [comment]
Your last commit appears to have removed all the changes.

**Comment by chrisinajar** [comment]
This is an empty PR which was apparently a duplicate of another PR. The good news is that I am confident you'll be able to open a PR if you come back and complete the work.

**Pull request closed without merging**
