### PR TITLE
Fix boss core drops

### PR DESCRIPTION
**Pull request by ProstoSanja**
As @haganeko told, fixing boss drop tables.
Every boss: 1 item combiner
T1: 5x reflex core  + farming core if hero has not got it yet
T2: 5x upgrade core 1
T3: 5x upgrade core 2
T4: 5x upgrade core 3
T5: 5x upgrade core 4
T6: 7x upgrade core 4
Changes suggestions are welcome

### CODE REVIEW

**Comment by ProstoSanja** [comment]
I just fixed items by changing them, I did not rewrite the mechanics of distribution

**Comment by Chronophylos** [comment]
Check #102

**Comment by Chronophylos** [comment]
Also don't do things in a `Fix boss core drops`-PR that aren't about fixing boss core drops.

**Comment by ProstoSanja** [comment]
yes it was a misclick, commited to wrong branch, i am trying to revert

**Comment by chrisinajar** [comment]
T1: 5x reflex core + farming core if hero has not got it yet

Every hero is supposed to get 1 farming core and 1 reflex core, each from one of the two teir 1 bosses near them.

**Pull request closed without merging**
