### PR TITLE
Map Changes

### PR DESCRIPTION
**Pull request by l34Um1**
Switches ancient, medium, easy camp location, moved boss arena
entrances, added path in the high ground area

### CODE REVIEW

**Comment by warpdragon** [comment]
I'm just gonna download this, pretty it up, and fix the conflict 
🗡  <-- it's a knife

**Comment by Chronophylos** [comment]
I heard you want to add in my changed for the farming cave as well.

**Comment by warpdragon** [comment]
yeah so Chris you should merge Chrono's pull request (if you want) first. then i'll just apply baumi's changes over it. and repaint the terrain.

**Comment by chrisinajar** [comment]
Closing in favor of warpdragon rebasing the changes on top of chrono's

**Pull request closed without merging**
