### PR TITLE
Reflex Spellicons

### PR DESCRIPTION
**Pull request by imaGecko**
Parity between icons and spellicons for reflex items

### CODE REVIEW

**Comment by Trildar** [comment]
Pfft. I just made a branch for this. I got ninja'd so hard. We don't really need pips in the spellicons version though, since those are buff icons.
Speaking of pips, the Crystals are missing pips.

**Comment by imaGecko** [comment]
They're stealing or jooooohbs

I just wanted them to be equal, pips won't be inside the modifier circle anyways

**Comment by warpdragon** [comment]
travis is being a total jerk these days.

**Comment by imaGecko** [comment]
#1058 fixes all the failing

**Pull request merged**
