### PR TITLE
Items to 5 project - items R-V

### PR DESCRIPTION
**Pull request by Minnakht**
Considerably more finished now.

Includes upgrade paths up to tier 5 for Linken's Sphere, Rod of Atos, Sange and Yasha, Shroud of Shadows, Solar Crest, Veil of Discord and Vladmir's Offering.

### CODE REVIEW

**Comment by chrisinajar** [comment]
rebased on upstream master

**Comment by imaGecko** [comment]
I do not know why travis fails

**Comment by Trildar** [comment]
```
/home/travis/build/OpenAngelArena/oaa/scripts/test/special-values.test.js:277
      var itemNames = Object.keys(entry).filter(a => a !== 'values');
                             ^
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /home/travis/build/OpenAngelArena/oaa/scripts/test/special-values.test.js:277:30
    at Array.forEach (native)
    at Test.<anonymous> (/home/travis/build/OpenAngelArena/oaa/scripts/test/special-values.test.js:275:23)
    at Test.bound [as _cb] (/home/travis/build/OpenAngelArena/oaa/node_modules/tape/lib/test.js:66:32)
    at Test.run (/home/travis/build/OpenAngelArena/oaa/node_modules/tape/lib/test.js:85:10)
    at Test.bound [as run] (/home/travis/build/OpenAngelArena/oaa/node_modules/tape/lib/test.js:66:32)
    at Test._end (/home/travis/build/OpenAngelArena/oaa/node_modules/tape/lib/test.js:154:11)
    at Test.bound [as _end] (/home/travis/build/OpenAngelArena/oaa/node_modules/tape/lib/test.js:66:32)
    at Test.<anonymous> (/home/travis/build/OpenAngelArena/oaa/node_modules/tape/lib/test.js:153:40)
```
Possibly some syntax error in KVs or something.

**Comment by Chronophylos** [comment]
Yeah it's trying to build the Item Tree to check item costs and upgrade paths

**Comment by imaGecko** [comment]
Vladimirs are missing closing squigglies (what are they even called?)

**Comment by Chronophylos** [comment]
```
  ✖ cost is set correctly in kv for item_urn_of_shadows_5
    operator: equal
    expected: 25875
    actual:   33875
```
```
  ✖ cost is set correctly in kv for item_urn_of_shadows_4
    operator: equal
    expected: 13875
    actual:   5875
```
```
item_shroud_3 is missing a title                                 - Add the key: "dota_tooltip_ability_item_shroud_3"
item_shroud_3 is missing a description                           - Add the key: "dota_tooltip_ability_item_shroud_3_description"
item_shroud_4 is missing a title                                 - Add the key: "dota_tooltip_ability_item_shroud_4"
item_shroud_4 is missing a description                           - Add the key: "dota_tooltip_ability_item_shroud_4_description"
item_vladmir_2 is missing a title                                - Add the key: "dota_tooltip_ability_item_vladmir_2"
item_vladmir_2 is missing a description                          - Add the key: "dota_tooltip_ability_item_vladmir_2_description"
```

**Comment by imaGecko** [comment]
those costs cannot be right

**Comment by Minnakht** [comment]
Honestly, neither of them are. The ones I make are $previoustier + 1500/3500/8000/20000, meanwhile Travis would rather add... some other values at each tier, probably reflecting the recipe costs changed like a month ago. 

chris has a script to auto-amend all the costs, so it's not a big deal. They'll be fixed when they will. For now let them be consistently wrong.

**Comment by Minnakht** [comment]
also @Chronophylos pls I can read Travis logs myself

**Comment by Minnakht** [comment]
WOOO! It's ready!

**Comment by imaGecko** [comment]
i think the wip tag can be taken off

**Pull request merged**
