### PR TITLE
Martyrs Mail, HotD, gitignore and small fixes

### PR DESCRIPTION
**Pull request by imaGecko**
Add Martyrs Mail 3 and 4
Add Helm of the dominator 1-5
Fix AC 1 Icon name
Fix level 5 SnY being level 4
Remove resource folder from gitignore (shouldn't be there in the first place according to trildar)

### CODE REVIEW

**Comment by Haganeko** [comment]
Add HotD too please?

**Comment by imaGecko** [comment]
They do have parity. As per old progression they are 1 level behind in exchange for the better effect.

**Comment by Haganeko** [comment]
Better how? It's a sidegrade. Loses the damage reflection and gains heal. If anything the effect of blade mail is stronger.

**Comment by imaGecko** [comment]
I am not aware of martyrs mail losing damage reflection

**Comment by Haganeko** [comment]
It was originally implemented with reflection by mistake. That has been fixed.

**Comment by imaGecko** [comment]
if you could point me to the PR where reflection was removed. I can only see the reflection being fixed to work properly

**Comment by Haganeko** [comment]
I thought the fix had been done but it hasn't. I'll open an issue for it.

**Comment by imaGecko** [comment]
changed mm files to work with #1227

**Comment by imaGecko** [comment]
Fixed nonexistent conflict

**Pull request merged**
