### PR TITLE
Map stuff

### PR DESCRIPTION
**Pull request by warpdragon**
try this one

### CODE REVIEW

**Comment by warpdragon** [comment]
goddamnit travis!

**Comment by Haganeko** [comment]
Apparently there's something wrong with hero_selection.js
You didn't edit it, though... Also your prefab files are missing a newline at the end I think.

**Comment by warpdragon** [comment]
yeah prefabs are 3D models so i'm not sure where i'd put one of those "new lines" you speak of.

**Comment by warpdragon** [comment]
it might be because now there's 1 too many maps? but that's not it either cuz that would have been triggered by my first commit, not the second.

**Comment by warpdragon** [comment]
i only opened it,  deleted one light source, and saved it...

**Comment by warpdragon** [comment]
trav

**Pull request merged**
