### PR TITLE
Bloodstone HP and Mana nerf

### PR DESCRIPTION
**Pull request by DarkoniusXNG**

### CODE REVIEW

**Comment by lovesmuffins** [comment]
I really don't think we should change this until we know whether or not spellcasters got buffed/nerfed from 7.26

**Comment by LeighJoseph** [comment]
I'm pretty sure they have been buffed

**Comment by DarkoniusXNG** [comment]
It needs a nerf because everyone buys it. If everyone buys it means its op.
It doesn't matter if Valve changes anything, amount of HP and mana this item gives should be equal to Octarine Core.

**Comment by POCKETMONEY99** [comment]
This is good. The HP and Mana Increase was only relevant before bloodstone gave spell amp.

**Pull request closed without merging**
