### PR TITLE
Hero Buffs 

### PR DESCRIPTION
**Pull request by POCKETMONEY99**
**Hero buffs**

Crystal Maiden
- Crystal Nova mana cost reduced from levels 1-4
- 20 talent Freezing field damage increased
- 25 talent Crystal Nova damage increased

Dark Willow
- Shadow Realm Cooldown rescaled. 
- Beldam cooldown reduced at levels 2 and 
- bedlam damage increased at levels 2 and 3.

Death Prophet
- Crypt Swarm Damage rescaled

Disruptor
- Thunderstrike cooldown rescaled
- Glimpse Cooldown rescaled
- Static Storm Cooldown reduced.

Doom
- Doom cooldown reduced
- Doom duration reduced (Minor nerf)

Enigma
- Black hole cooldown rescaled

Legion Commander
- Duel cooldown reduced

Lina

- Dragon Slave damage increased
- Laguna Blade cooldown reduced
- Laguna Blade damage increased levels 2 and 3.

Lcyan
- Feral Impluse Damage increased
- Shapeshift cooldown reduced

Mirana
- Leap charge restore time reduced

Night Stalker

- Void cooldown set at 8 seconds
- Void slow duration during day increased
- Void Slow duration during night rescaled

Queen of Pain
- Sonic Wave cooldown reduced

Razor

- Eye of the Storm mana cost reduced
- Static link cooldown reduced
- Static Link damage drained increased

Sand King

- Epicenter cooldown reduced
- Epicenter damage increased
- Epicenter attackspeed slow now scales

Spectre

- Haunt cooldown rescaled

Treant Protector

- Overgrowth cooldown deacreased
- Base movement speed increased from 270 to 285. (Map is very poorly designed for treant protector).

Tusk

- Tag team damage increased at OAA levels
- Mana cost set to 70 at all levels
- Walrus Punch Cooldown set to 12 seconds.

### CODE REVIEW

**Comment by POCKETMONEY99** [comment]
There are some other changes I wanted to do but didnt know how. The first was to make night stalker void deal full damage in the day. And increase queen of pains level 15 attackspeed talent from +40 to +70 and increase natures prophet attack speed talent from +40 to +140

**Comment by DarkoniusXNG** [comment]
You deleted butterfly and diffusal blade files by accident I presume. I know that you want to make seperate pull requests for items and talents but plz be careful next time what you are deleting.

**Comment by POCKETMONEY99** [comment]
> 
> 
> You deleted butterfly and diffusal blade files by accident I presume. I know that you want to make seperate pull requests for items and talents but plz be careful next time what you are deleting.

Sorry I wanted to revert file i changed rather then delete it. Would I instead change the numbers back to what I wanted them to be?

**Comment by DarkoniusXNG** [comment]
When you want to revert stuff you changed, just change it back how it was.

**Pull request closed without merging**
