### PR TITLE
Post april major

### PR DESCRIPTION
**Pull request by l34Um1**
The map currently breaks the game and I don't know why. I assume one of the zones is wrong. Need help with it.

### CODE REVIEW

**Comment by l34Um1** [comment]
So travis is telling me that all sorts of things are wrong but none of them are files I actually touched so I dunno what to do about it.

**Comment by SquawkyArctangent** [comment]
it's because we haven't caught up to vanilla dota yet and those values haven't beem marked as changed for oaa, dark has a pull request that fixes that

**Comment by l34Um1** [comment]
Ok that's good. Map still breaks the game though lol

**Comment by lovesmuffins** [comment]
is this a new map or old map?

**Pull request merged**
