### PR TITLE
Fixed Moriah Dagger duplicate Key Values

### PR DESCRIPTION
**Pull request by ThatMusicWriter**
I _think_ I removed the changes I made from my last PR properly. If not, I'll fix it right away. Either way, I fixed both levels of the dagger so they don't have duplicate values.

### CODE REVIEW

**Comment by ThatMusicWriter** [comment]
Sorry about the extra commits, trying to learn ways to jerry-rig extra pulls.

**Comment by Haganeko** [comment]
Try not to commit to master next time.

**Comment by Haganeko** [comment]
Will same you a load of trouble.

**Comment by ThatMusicWriter** [comment]
OK, thanks.

**Comment by Trildar** [comment]
You can also do `git branch [branch-name] OpenAngelArena/master`. Where [branch-name] is what you want to name the new branch. Assuming you followed the doc and added this repo as a remote under the name OpenAngelArena.

Then `git checkout [branch-name]` and do the additional work there.

**Pull request closed without merging**
