### PR TITLE
Simple Bosses #1 Juxtapose + Geostrike

### PR DESCRIPTION
**Pull request by Chronophylos**
From #865 
Unit name: `npc_dota_boss_simple_1`
Ability 1: `boss_juxtapose`
Ability 2: `boss_geostrike`
Ability 3: `boss_resistance`

### CODE REVIEW

**Comment by imaGecko** [comment]
Shouldn't the abilities only have 1 level?

**Comment by Chronophylos** [comment]
Yeah

**Comment by chrisinajar** [comment]
Needs these tooltips:
 * dota_tooltip_ability_boss_geostrike
 * dota_tooltip_ability_boss_geostrike_description
 * dota_tooltip_ability_boss_juxtapose
 * dota_tooltip_ability_boss_juxtapose_description

**Comment by warpdragon** [comment]
"models/creeps/lane_creeps/creep_bad_melee/creep_bad_melee.vmdl" nice! I love using weird, unused models like this!

**Pull request merged**
