### PR TITLE
Strafe Balance

### PR DESCRIPTION
**Pull request by Nortlen**
Increased cooldown of Strafe, so it isn't zero.

### CODE REVIEW

**Comment by imaGecko** [comment]
Can very easily agree with the change

**Comment by Haganeko** [comment]
Seems okay.

**Comment by l34Um1** [comment]
keep at 15

**Comment by Haganeko** [comment]
It does already progress the AS value.

**Comment by Nortlen** [comment]
Changed the cooldown to stay at 15

**Pull request merged**
