### PR TITLE
Oaa dashboard

### PR DESCRIPTION
**Pull request by carlosrpg**
Fix Issue #2165

### CODE REVIEW

**Comment by carlosrpg** [comment]
image

**Comment by chrisinajar** [comment]
Does it only show up when you're holding alt?

**Comment by carlosrpg** [comment]
It was in the ticket as it was done on other game I think

**Comment by chrisinajar** [comment]
that was not an answer to my question at all, hahahahah

I assume that means "yes" since the ticket says `Picture taken from Black Star. Similar to this. The menu below the clock shows up when you hold alt. `

**Comment by carlosrpg** [comment]
oh, yep, the answer  is Yes

**Pull request merged**
