### PR TITLE
Boss changes

### PR DESCRIPTION
**Pull request by KarmaticNeutral**
Shielder and Twin AI improvements

Shielder:
   Make him work the way he was always intended to (EG attacks highest damage source)

Twin:
   Melee twin should always try to attack the enemy that is furthest from his ranged counterpart
   Death of Melee Counterpart needs to either kill the Ranged one or not give cores.

### CODE REVIEW

**Comment by KarmaticNeutral** [comment]
`[   Developer            ]: scripts/vscripts/libraries\event.lua:31: attempt to call field 'fn' (a nil value)
[   Developer            ]: stack traceback:
[   Developer            ]: 	scripts/vscripts/libraries\event.lua:31: in function 'broadcast'
[   Developer            ]: 	scripts/vscripts/events.lua:80: in function <scripts/vscripts/events.lua:62>
[ W VScript              ]: Script Runtime Error: scripts/vscripts/libraries\event.lua:31: attempt to call field 'fn' (a nil value)
[ W VScript              ]: stack traceback:
[ W VScript              ]: 	scripts/vscripts/libraries\event.lua:31: in function 'broadcast'
[ W VScript              ]: 	scripts/vscripts/events.lua:80: in function <scripts/vscripts/events.lua:62>`

Is my error in  twin.lua

And I have a bad player index in shielder.lua

**Comment by KarmaticNeutral** [comment]
Well game crashes now when you attack the melee twin SO... ya...

**Comment by warpdragon** [comment]
"Prevent boss stacking due to lingering idiot" love this commit.

**Comment by Haganeko** [comment]
"Removed Crash - Still Broken" is also gold.

**Comment by chrisinajar** [comment]
Closing dead PRs

**Pull request closed without merging**
