### PR TITLE
Added Audiovisuals to Chargers Charge

### PR DESCRIPTION
**Pull request by Chronophylos**
Channel Start: [`"Boss_Charger.Charge.Begin"`](https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/01/Nether_Strike_pre_cast.mp3)
During Charge: `"Boss_Charger.Charge.Movement"` -- Spirit Breakers Charge Movement
When hitting a Hero: [`"Boss_Charger.Charge.HeroImpact"`](https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/08/Charge_of_Darkness_target.mp3)
When hitting a Tower: [`"Boss_Charger.Charge.TowerImpact"`](https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/88/Nether_Strike_cast.mp3)

Particle when a tower was hit

### CODE REVIEW

**Comment by Trildar** [comment]
Not sure how long the charge start sound is, but we probably want to stop it when charge is interrupted, gives feedback that something is being interrupted at least some of the time.

**Comment by Chronophylos** [comment]
What sound do you want?

**Comment by allanvbhg** [comment]
We had the sounds right? I have send then

**Comment by Chronophylos** [comment]
All sounds are in

**Comment by Chronophylos** [comment]
As long as no one has another request this is ready

**Comment by allanvbhg** [comment]
I wane see it in game haha

**Comment by Trildar** [comment]
If you meant what sound I want. I don't want a sound, I just want the start sound to be interrupted cause it currently always plays to completion.

**Comment by Chronophylos** [comment]
You mean when the channel is finished?

**Comment by Haganeko** [comment]
He means if the boss gets interrupted out of his channeling attempt.

**Comment by Trildar** [comment]
You could end it unconditionally OnChannelFinish, but that might also make the sound not complete in 3rd phase since he charges so fast. I was thinking just when it's interrupted.

**Comment by Chronophylos** [comment]
Like this?

**Comment by Trildar** [comment]
Yep

**Comment by imaGecko** [comment]
could have someone do some basic edits to the soundfile to make it fit for the third phase

**Comment by Chronophylos** [comment]
What would you suggest?

**Comment by imaGecko** [comment]
I think the nether strike windup would still sound good if you cut off a bit off the end. then make the end a bit smoother with changing the pitch. Later I'll see if I can just create something that roughly shows what I mean

**Comment by chrisinajar** [comment]
Lets give this a go a tweak from here. Once we get more sounds in the game people will be more inclined to improve them!

**Comment by imaGecko** [comment]
any idea how I can get the soundfile?

**Comment by Chronophylos** [comment]
Give me a minute I'll send it to you in Discord

**Comment by imaGecko** [comment]
https://instaud.io/114P
I tried and failed

**Pull request merged**
