### PR TITLE
Fixed Wraith King reincarnation (#201)

### PR DESCRIPTION
**Pull request by Chronophylos**
Fixed points increasing during reincarnation
Fixed WK not respawning during duel

###### Note: I haven't tested this.

### CODE REVIEW

**Comment by ProstoSanja** [comment]
Hello, this ruined duels, isreincarnating should be called with arguments, now they dont end

[ W VScript                ]: Script Runtime Error: scripts/vscripts/components\points\points.lua:35: IsReincarnating called with 0 arguments - expected 1
[ W VScript                ]: stack traceback:
[ W VScript                ]: 	[C]: in function 'IsReincarnating'
[ W VScript                ]: 	scripts/vscripts/components\points\points.lua:35: in function 'fn'
[ W VScript                ]: 	scripts/vscripts/libraries\event.lua:31: in function 'OnHeroKilledEvent'
[ W VScript                ]: 	scripts/vscripts/events.lua:331: in function 'OnHeroKilled'
[ W VScript                ]: 	scripts/vscripts/internal\events.lua:92: in function <scripts/vscripts/internal\events.lua:56>

**Comment by Chronophylos** [comment]
There is no argument in the docs.

**Comment by ProstoSanja** [comment]
But still script crashes at this point with logs I sent above
And removing this line fixed it, so we need to find g a sample somewhere

**Comment by ProstoSanja** [comment]
ive found the fix, it should be called like this
`keys.killed.IsReincarnating`
no : or ()
but now another problem appears, because of dul not allowing to respawn, he reincarnates, but stays dead at the same time, and duel doesnt end

**Comment by Chronophylos** [comment]
Enabling respawn and disableing respawn could fix it.

**Comment by ProstoSanja** [comment]
well , i am not into this mechanics, and dont even know where it is, so good luck further 🥇

**Comment by Chronophylos** [comment]
I should test things before I push them..
Thanks @ProstoSanja!

**Comment by Trildar** [comment]
I'm pretty sure it should be `keys.killed:IsReincarnating()`. Without colon or brackets would give you the function handle. The colon makes it call the function with a reference to its `self` object as a first argument. Hence why it's complaining of a lack of arguments.

**Comment by ProstoSanja** [comment]
i tested 
`keys.killed.IsReincarnating` and it worked, duel didnt end when he was reincarnating

**Comment by Chronophylos** [comment]
Ohh thats what `:` and `.` mean!

**Comment by Trildar** [comment]
@ProstoSanja Just FYI, if you didn't test if duels could still end at all, probably what happened is that `keys.killed.IsReincarnating` gives the function handle and in Lua, a function handle would be considered truthy and so that block just always runs (so long as `keys.killed` actually has some value or method called `IsReincarnating`).

**Comment by chrisinajar** [comment]
: passes a self context to the method, . does not. Functions defined with a : have a "secret" first parameter for self built in.

function ASDF:Add(b)
  return self + b
end

is the same as

function ASDF.Add(a, b)
  return a + b
end

and can be run like

ASDF.Add(1, 3) -- returns 4


All valve functions expect a context.

**Comment by Chronophylos** [comment]
Ah, thanks.

**Comment by SphereKatzen** [comment]
It's a method call, so there is an argument, it must not be being called on the correct object. Try storing the hero in variable first maybe?

**Pull request merged**
