### PR TITLE
make aether lens scale better

### PR DESCRIPTION
**Pull request by OTAJumperjay**
Update tooltip_lycan_boss.txt - can i somehow remove this change ? i want to do the tooltips in a seperate pr... i used this to open a new branch ... could someone also tell me how to open new branches without having to change a file on the github server.. i'm sure there is a better way to open one

### CODE REVIEW

**Comment by OTAJumperjay** [comment]
stupid me okay i just found the big AF "new" button ... and i do work locally i just didn't know how to open a different branch lul

**Comment by Haganeko** [comment]
Should also take a look at the shapeshift tooltip. It's pretty bad.
Cast range should be an integer. Try
250/325/400/550/700

**Comment by Haganeko** [comment]
Ah. Switch to master before creating new branches.

**Comment by OTAJumperjay** [comment]
master is horribly outdated... how can i update my master ?

**Comment by OTAJumperjay** [comment]
shapeshift doesn't have a cast range.. what are you talking about

**Comment by OTAJumperjay** [comment]
also i changed the cast range from INTEGER to FLOAT .. that should do it

**Comment by Haganeko** [comment]
That's not the solution. First, the item shouldn't scale perfectly linearly. Later levels can and should be worth more.
Second, float cast range might do weird things.

**Comment by OTAJumperjay** [comment]
okay well didn't work anyway ... i'll do your suggestion then i guess

**Comment by OTAJumperjay** [comment]
250/325/400/550/700 that is not good either i think.. like this it's 250 + 75 + 175 + 150 + 150

**Comment by l34Um1** [comment]
Items shouldn't scale 100% linearly. I don't see much of an issue with the current scaling. Yes it's a great value pickup and doesn't need to be maxed out right away but if it wasn't I don't think it would see play.

**Comment by OTAJumperjay** [comment]
250 375 400 575 700... that is the current one from lvl 2 to lvl 3 it is +25

**Comment by OTAJumperjay** [comment]
then +175 to lvl 4 and +125 to lvl 4

**Comment by Haganeko** [comment]
Jumperjay
250/325/400/550/700 is
+75/+75/+150/+150
In fact, 250/325/400/525/700 might be even better.

**Comment by OTAJumperjay** [comment]
oh ye .. i guess.. what do you think @l34Um1

**Comment by Haganeko** [comment]
250/325/425/550/700
+75/+100/+125/+150

**Comment by l34Um1** [comment]
Sure, let's go with that last one. Current early scaling is actually a typo, my b

**Comment by OTAJumperjay** [comment]
oh i need to update the other aether lens files as well .. guess i learn every day

**Pull request merged**
