### PR TITLE
Creep + Gold Rework

### PR DESCRIPTION
**Pull request by Haganeko**
To do:

- [x] Add new camps and rework gold
- [x] Rebalance creeps
- [x] Add creeps to map
- [x] Change passive GPM
- [x] Rework boots bonus gold
-  Test all that stuff
-  Adjust gold based on testing
-  Adjust creeps based on testing
-  Adjust boots based on testing

### CODE REVIEW

**Comment by Haganeko** [comment]
Waiting on Baumi to look at boots, and warp to do the map thing.

**Comment by warpdragon** [comment]
i merged this with mine. you can merge whenever and when my map goes in it shouldnt' create a conflict 💯

**Comment by Haganeko** [comment]
Can't really merge it in until the map is ready tho.

**Comment by warpdragon** [comment]
Ok yeah i will try and finish my PR tonight. I have a LOT more i wanna do but i need to make a new pr for that

**Comment by Haganeko** [comment]
Merge me for testing

**Comment by Haganeko** [comment]
@SquawkyArctangent Passive experience during minute n should be
`(45*n^2 + 67*n + 2450)/100`
Or, in 5 second ticks,
`(15*k^2 + 103*k + 116401)/5760`
on tick k

**Pull request merged**
