### PR TITLE
Added -getpos command to print vector of current position

### PR DESCRIPTION
**Pull request by darklordabc**
Simple and straightforward tool to find what position the hero is in, useful if you want to know vector coordinates of a location.

### CODE REVIEW

**Comment by chrisinajar** [comment]
Can you make it print to chat as well for multiplayer testing?

**Comment by darklordabc** [comment]
Yeah I can just add sendcustomgamemessage

**Comment by darklordabc** [comment]
Although it won't work on multiplayer yet for the v reasons we talked about.

**Comment by darklordabc** [comment]
Updated

**Pull request merged**
