### PR TITLE
Removed leading whitespaces and tabs, fixed new lines

### PR DESCRIPTION
**Pull request by Chronophylos**
Colored Lich Sacrifice's changes to vanilla

### CODE REVIEW

**Comment by chrisinajar** [comment]
conflicts...

**Comment by Haganeko** [comment]
Well he did edit almost all the item files
Why remove the whitespace, though? It seems easier to read with than without.

**Comment by chrisinajar** [comment]
Indentation is usually used to show hierarchy, where here it's completely arbitrary. I approve :+1:

**Comment by Chronophylos** [comment]
@chrisinajar I resolved the conflicts

**Pull request merged**
