### PR TITLE
Sohei models (Warp/Carlos)

### PR DESCRIPTION
**Pull request by warpdragon**
Got some pants using FollowEntity(). Walking animation is bugged for some reason.

### CODE REVIEW

**Comment by Haganeko** [comment]
Couldn't reuse the wearables library from Frostivus?

**Comment by warpdragon** [comment]
We're going to need to do that eventually, but i'm tired. Can someone look at that walking animation that'd be so fantastic

**Comment by warpdragon** [comment]
Someone should definitely add the CosmeticLib into our repo. Without this  I am unable to do anything outside of Juggernaut-only cosmetics.

**Comment by warpdragon** [comment]
https://youtu.be/3580gaK6ZK4

**Comment by Haganeko** [comment]
Wouldn't a staff look better than a polearm, especially with an overhead swing?

**Comment by warpdragon** [comment]
meh. i asked baumi and he wanted this. the good news is we can change it to anything we want. it could be a giant lolly

**Comment by OTAJumperjay** [comment]
🤔 could be worth thinking about for an april fools update

**Comment by l34Um1** [comment]
I don't mind a staff. Actually someone suggested something like this and I think it would be cool: http://www.nihonzashi.com/bokken_shinai_pictures/purpleheartwoodtetsubo.jpg

**Comment by FelPac** [comment]
An inspiration Model I have made with blender
https://imgur.com/a/Yldpu

**Comment by warpdragon** [comment]
Sohei is ready to roll!

**Comment by carlosrpg** [comment]
I approve this message!

**Pull request merged**
