### PR TITLE
Balance

### PR DESCRIPTION
**Pull request by l34Um1**

### CODE REVIEW

**Comment by Haganeko** [comment]
On meteor hammer, why not double level 1 as well?

**Comment by l34Um1** [comment]
actually yeah good point.

**Comment by Haganeko** [comment]
You redid the nerf you undid, in addition to the new one.
Also, you sure we should alter vanilla values?

**Comment by l34Um1** [comment]
You know I don't like altering vanilla values but Naga is incredibly oppressive. I am also aware I redid the nerf. She would be overpowered with vanilla level 3 ultimate. I honestly expect her to still be very strong, just not stupidly broken.

**Comment by Haganeko** [comment]
Ah, okay. Not refreshing the Core for duels would also reduce her power level, no?

**Comment by l34Um1** [comment]
Yes but she would still be strong. Naga is super op atm.

**Pull request merged**
