### PR TITLE
Lucience stats

### PR DESCRIPTION
**Pull request by POCKETMONEY99**
Given Lucience bonus all stats instead of bonus damage. Made luciences arua radius 1200 (This is the default aura radius). 

Decreased movespeed scaling on Lucience

### CODE REVIEW

**Comment by DarkoniusXNG** [comment]
LOL you cant add stats like that. It needs to be added in lua. It needs code. I think I told you guys that I will eventually fix this.

**Comment by POCKETMONEY99** [comment]
> 
> 
> LOL you cant add stats like that. It needs to be added in lua. It needs code. I think I told you guys that I will eventually fix this.

Didnt you just do this with refresher?

**Comment by DarkoniusXNG** [comment]
https://github.com/OpenAngelArena/oaa/commit/dd52e6eba4e2dc4769385c201c06e93c6a413b44#diff-8018aefcf13d134b434d9df69367108d Look at the bottom file

**Comment by POCKETMONEY99** [comment]
> 
> 
> [dd52e6e#diff-8018aefcf13d134b434d9df69367108d](https://github.com/OpenAngelArena/oaa/commit/dd52e6eba4e2dc4769385c201c06e93c6a413b44#diff-8018aefcf13d134b434d9df69367108d) Look at the bottom file

Tried giving the item all stats.

**Comment by DarkoniusXNG** [comment]
That will work. Can you also nerf the ms bonus now? 20% is ok, but other levels are not. 60% is dumb for example.

**Comment by DarkoniusXNG** [comment]
All that is left for you to do are tooltips. https://github.com/OpenAngelArena/oaa/blob/master/game/resource/English/ability/items/tooltip_lucience.txt
If you are not sure how to do this, I will help u.

**Pull request merged**
