### PR TITLE
Second Day Spiders: Boss - Code

### PR DESCRIPTION
**Pull request by TideSofDarK**
#2116

### CODE REVIEW

**Comment by TideSofDarK** [comment]
I'm not sure about tier and other stuff so for now you can spawn the boss from console
**npc_dota_boss_spiders**
Let me know if it has to be somewhere in bosses.lua or smth

**Comment by chrisinajar** [comment]
I spawned it and it doesn't seem to ever agro. Haven't debugged the issue yet... You can make him spawn in the tier 1 pit by adding him to bosses.lua

**Comment by TideSofDarK** [comment]
@chrisinajar what do you mean by aggro?
IIRC this boss is intended to slowly walk around and shoot two kinds of projectiles.
tested it many times by spawning it manually and adding some friendly heroes so he tries to stack them up

Will ensure this mechanic works soon

**Comment by TideSofDarK** [comment]
https://streamable.com/w79kn
Still works for me

**Comment by l34Um1** [comment]
The eggs should be affected by spells. The bombs are lacking an explosion. Seems ready other than that.

**Comment by l34Um1** [comment]
Ready to merge imo

**Pull request merged**
