### PR TITLE
ItemSellable 0 for neutral items

### PR DESCRIPTION
**Pull request by warpdragon**

### CODE REVIEW

**Comment by warpdragon** [comment]
tested. doesn't crash game.

**Comment by warpdragon** [comment]
Community reports some items are sellable up to 10  seconds after purchase for 0 gold$. 

Just added "ItemSellable" "0" to neutral item kv files.

I was able to test selling an Eye of the Vizier after purchase. no crash. no errors. no selling allowed.

**Comment by warpdragon** [comment]
o wow u caught that mistake. nice!

**Comment by DarkoniusXNG** [comment]
not a mistake, just my OCD doing work

**Pull request merged**
