### PR TITLE
Quick icon fixes070517

### PR DESCRIPTION
**Pull request by RionTwist**
Fixed icons for Scythe, Refresh, Manta, Shiva & Lucience movespeed icons. @chrisinajar .

### CODE REVIEW

**Comment by warpdragon** [comment]
good stuff

**Comment by warpdragon** [comment]
hey if you get this message can you copy these icons:
```crimson guard also is missing the modifier icon
linkens active as well
ok seems to be a bunch more
ok modifier icons are missing for: scythe of vyse, solar crest (not for medalion), mjollnir, rod of atos, lotus orb, linkens sphere, crimson guard, assault cuírass, silver edge (again shadow blade is fine), butterflys flutter, drums of endurance as well as pipe of insight
oh and abyssal blade
and radiance burn```
into the /spellicons/custom directory?

If not it's fine.

**Comment by RionTwist** [comment]
flipped those items over (plus a few others I found) to the spellicons directory and committed. I don't have to re-make the pull request, it should pickup on the new committed pieces, right?

**Comment by warpdragon** [comment]
Correct

**Comment by warpdragon** [comment]
As long as it hasnt yet been merged, which is indeed the case

**Pull request merged**
