### PR TITLE
Less crash, more game

### PR DESCRIPTION
**Pull request by imaGecko**
Added missing baseclasses to BKB and Cyclone

### CODE REVIEW

**Comment by Haganeko** [comment]
ImaGecko for AntiChrono 2017

**Comment by Chronophylos** [comment]
wat

**Comment by Haganeko** [comment]
Unbreaker of things.

**Comment by warpdragon** [comment]
I'm the BREAKER now!

**Comment by imaGecko** [comment]
Warp for chrono 2017?

**Comment by Chronophylos** [comment]
a breaker
a breaker

**Comment by imaGecko** [comment]
spirit breaker set nao
volvo plis

**Pull request merged**
