### PR TITLE
Any last words?

### PR DESCRIPTION
**Pull request by warpdragon**
removed SC from npc_items_custom

### CODE REVIEW

**Comment by Chronophylos** [comment]
"RIP Shivas Cuirass
may we never see you again"

like this?

**Comment by imaGecko** [comment]
o7

**Comment by chrisinajar** [comment]
When can we get tier 4 and 5 of AC and SG to replace this D:

**Comment by imaGecko** [comment]
soon™

**Comment by chrisinajar** [comment]
Should probably remove the source files and translations too...

**Pull request merged**
