### PR TITLE
Rebalanced Invoker

### PR DESCRIPTION
**Pull request by warpdragon**
### What?
Increase Invoker's linear progression to exponential progression after Hero Level 25. 

### Why?
All heroes are supposed to be fun to play, even if they're bad. Invoker is neither good nor fun.
Invoker was balanced initially by myself about a year ago and I was incredibly careful to keep his values low by using linear progression. This has proven to be very bad for the hero so I am attempting to correct this.

### How?
1. Increase Invoker's late game spell damage values as well as forge spirit's HP/Atk values by about 50% by max level by using exponential progression after Hero Level 25.
2. Reduce Invoker's late game crowd-control durations by about 10-25% by max level to compensate for his increased damage.

### Notes
After putting in the pull request, I noticed Travis was failing me for changing vanilla values. I have not changed vanilla values. I have concluded that Travis is throwing false positives. The likely reason is anyone's guess.

### CODE REVIEW

**Comment by warpdragon** [comment]
Those are the vanilla values, Travis!!!!

**Comment by Melongod** [comment]
The scary thing about Invoker is that he has 10 spells. Ideally, the optimal balance for that hero is to have all of his spells be slightly sub-par so that good Invoker players can't just abuse the shit out of him.

**Comment by warpdragon** [comment]
I agree. If u compare this new progression with other heroes you will see that has been taken into account. 50% increase post lvl 25 is considerably lower than that of the average hero ability.

**Comment by warpdragon** [comment]
I agree. The numbers i have come up with are well within that scope.

**Comment by imaGecko** [comment]
You did edit the 8th value at some points which is still a vanilla value, since aghs adds 1 level

**Comment by warpdragon** [comment]
merge me!

**Comment by Haganeko** [comment]
Invoker was actually somewhat good lol

**Comment by warpdragon** [comment]
yeah i noticed. but i still think this is better. he does more damage without having those 10 billion decade crowd control durations.

**Comment by warpdragon** [comment]
Nope. Travis is full of shit. I just triple checked. I am not changing goddamn fucking vanilla values!!!!!!
RAGE

**Comment by warpdragon** [comment]
Fuck this shit

**Comment by Haganeko** [comment]
Why close it?

**Pull request closed without merging**
