### PR TITLE
Big icon push04052017

### PR DESCRIPTION
**Pull request by RionTwist**
Added in custom Aghs icon progression, as well as basic pips for all standard dota items whose names begin with A, B, C or D. Also added pips to Luscience, Trump's Fist, Shiva's Curass, Stoneskin, and Radience.

### CODE REVIEW

**Comment by spar36** [comment]
dude!!! awesome!!!

**Comment by warpdragon** [comment]
https://youtu.be/4jBDnYE1WjI?t=85

**Comment by Haganeko** [comment]
There are conflicts... I wonder why?

**Comment by warpdragon** [comment]
that should do it

**Comment by RionTwist** [comment]
I'm not sure what the conflict was, but glad it was that easy to fix.

**Comment by warpdragon** [comment]
well if anyone is fuckign with npc_item files between the time when he created the branch and when this PR gets merged it will cause conflicts.

**Comment by spar36** [comment]
apparently, someone did something with armlet. nothing a simple rebase couldn't fix.

**Comment by warpdragon** [comment]
we already fixed it, goober

**Pull request merged**
