### PR TITLE
Reflex Items now all start with max level ability.

### PR DESCRIPTION
**Pull request by ThatMusicWriter**
Ignore extra commits; my clone of the Github broke and I had to reset an entire folder. See "Files Changed" for actual changes.

### CODE REVIEW

**Comment by imaGecko** [comment]
Speaking of a mess

**Comment by ThatMusicWriter** [comment]
Indeed. My files seem to break when I don't update OAA often enough

**Comment by imaGecko** [comment]
Perhaps not updating correctly as it looks like

**Comment by ThatMusicWriter** [comment]
Indeed, because it literally added more file changes just now.

**Comment by ThatMusicWriter** [comment]
Learning code is fun. Github is misery.

**Comment by imaGecko** [comment]
a rebase would solve all of this

**Comment by chrisinajar** [comment]
Use hard reset and force push

**Comment by ThatMusicWriter** [comment]
Sorry, I don't have the knowledge to do that. I have branches identical to the base branch; I'll just redo this manually. It won't get rid of the weird commits, but I can fix that next week when I have the time to look up how and learn how to use this very unwieldy software. Sorry for any inconvenience.

**Pull request closed without merging**
