### PR TITLE
Fix OgreBoss - Add Silence Immunity

### PR DESCRIPTION
**Pull request by carlosrpg**

### CODE REVIEW

**Comment by imaGecko** [comment]
your file is named "tooltipe"

**Comment by imaGecko** [comment]
also stop doing work on your master branch

**Comment by chrisinajar** [comment]
`/tooltipe_siltbreaker_boss_immunity.txt` also shit commit history, please run `git fetch upstream` then `git rebase upstream/master`

**Comment by chrisinajar** [comment]
That was a really negative comment, I just want to say that you've been doing really great work lately. :D

**Comment by carlosrpg** [comment]
I was trying to fix my terrible branch history.
Thanks for the heads up. I should have done that before requesting the PR.

**Comment by chrisinajar** [comment]
fwiw, you can run `npm run test` to run the test cases locally to check stuff like ID numbers. `npm run spec` gives slightly different output for some errors

**Comment by carlosrpg** [comment]
Sorry guys, I was working on 3 branches (ogre,lycan,ControlParticles) and has being a while since I used git. So my branches got kind of fucked up.

**Pull request closed without merging**
