### PR TITLE
Cave minimap icons

### PR DESCRIPTION
**Pull request by warpdragon**
Minimap icons for the Cave. Thanks to Carlos for the code

### CODE REVIEW

**Comment by warpdragon** [comment]
Yup. Works. 
Preview

**Comment by chrisinajar** [comment]
Should you be able to see the enemy cave?

**Comment by warpdragon** [comment]
Sure whynot

**Comment by warpdragon** [comment]
I suppose we could make a slightly different modifier that only displays icons to allies

**Comment by warpdragon** [comment]
The counter argument would be that u can likewise see enemy boss icons so whynot cave too?

**Comment by Melongod** [comment]
You can see when enemies take cave by looking at the opened/closed gates

**Comment by Trildar** [comment]
Well, minimap is even less effort to look at. And the gates might just be removed entirely anyway as they don't really serve much purpose at this point.

**Comment by Haganeko** [comment]
You need to go look at/have wards to see the gates, no?

**Comment by Melongod** [comment]
nope

**Comment by carlosrpg** [comment]
I guess Rip Icons?

**Comment by chrisinajar** [comment]
we're removing the cave anyway

**Pull request closed without merging**
