### PR TITLE
item buffs and nerfs

### PR DESCRIPTION
**Pull request by TheUnholyWrath**
far sight cd buff and aoe scaling

butterfly worse level 2, more consistent scaling

### CODE REVIEW

**Comment by lovesmuffins** [comment]
you've kinda nerfed butterfly into the ground...
I agree it needs better scaling but it shouldn't be nerfed as well. It's an item that isn't really picked up due to MKB countering it's unique component. Most people either go into Yasha Sange/Kaya or stay diffusal. The one reason people may of picked it up was for the evasion vs bosses but you're also reducing that. I don't know how I feel about these changes overall.

**Comment by TheUnholyWrath** [comment]
> you've kinda nerfed butterfly into the ground...
> I agree it needs better scaling but it shouldn't be nerfed as well. It's an item that isn't really picked up due to MKB countering it's unique component. Most people either go into Yasha Sange/Kaya or stay diffusal. The one reason people may of picked it up was for the evasion vs bosses but you're also reducing that. I don't know how I feel about these changes overall.

seems like my title is pretty misleading, initially there were butterfly buffs. you're totally right, when i'm back i'll change it to something more reasonable

**Comment by TheUnholyWrath** [comment]
far sight nothing changed
butterfly might be more reasonable now, probably still needs fiddling
mkb probably doesnt need a nerf
idea for a glimmer cape change
yasha variants should have actual movement speed, this is less than actual

pretty happy to just remove anything too unreasonable/insignificant/completely off the mark. mostly just feelers for feedback

**Comment by lovesmuffins** [comment]
I'd actually really like it if MKB's chance would be the numbers getting the nerf. To make it so evasion isn't completely useless when your opponents first get the item.

Something like 55/60/65/70/75?

**Comment by TheUnholyWrath** [comment]
> I'd actually really like it if MKB's chance would be the numbers getting the nerf. To make it so evasion isn't completely useless when your opponents first get the item.
> 
> Something like 55/60/65/70/75?

the damage on the procs would have to be fiddled with if you want to do that, almost had the exact opposite idea with though, want to make mkb a bit more based on the proc, i was thinking about scaling it when changing but something much more mild, not sure yet maybe i'm the way i'm thinking is the wrong direction to move mkb to

**Comment by lovesmuffins** [comment]
As of right now, MKB is just a better version of Mjolnir, without the attack speed. I liked how you scaled the Mjolnir upwards and I think MKB should also start less to reflect that change. I don't think damage would have to be fiddled with that much as of right now it's powerful enough and your damage nerf could just be reverted.

**Comment by l34Um1** [comment]
Can you please take out the movement speed changes? Then I'll merge this.

**Comment by TheUnholyWrath** [comment]
yasha gives flat movement speed these changes are fine

**Pull request merged**
