### PR TITLE
Music player

### PR DESCRIPTION
**Pull request by ProstoSanja**
Current state
Need an image for play/pause in style of these 3 buttons on the left!
image

### CODE REVIEW

**Comment by ProstoSanja** [comment]
So yeah, chris, this is fully ready. The usage is as follows:
you declare songs in `music_list`,
then use `Music:SetMusic(i)` where `i` is a number from list.
Works everywhere, anyone can mute without affecting others and thats it. To stop playing you can just declare empty string, but i think thats unneeded

**Comment by ProstoSanja** [comment]
also for reference #32

**Comment by chrisinajar** [comment]
I'm going to make a release without this so that we can get it right and make it look nice.

Thanks a ton for doing the work on this, the music guys are going to be HYPED

**Comment by ProstoSanja** [comment]
Yeah, so like here's the final look of it, forgot to post it. And the last thing we need is just to add songs to game and play points for them in code. Everything else is ready.
unknown-1
unknown

**Comment by chrisinajar** [comment]
image

**Comment by chrisinajar** [comment]
Can you put an example mp3 in there from the soundcloud?

**Comment by ProstoSanja** [comment]
@chrisinajar example.code is in the second comment on this pull request. The file should be imported with this custom `.vsndets` or something like this format. I'll check today how to do it.

**Comment by ProstoSanja** [comment]
so it is `.vsndevts` and again instruction to use it:
1) import file (i'll add to this when i undertand how)
2) open `music_list.lua` and fill in the new files name, beautiful name and author
3) use `Music:SetMusic(i)` where `i` is a number from  `music_list.lua` this function works globally

**Comment by Chronophylos** [comment]
`.vsndevts` are pretty simple.
1. Put your `.mp3`, `.wav` or others in `/content/sounds/`
eg:
`/content/sounds/music/fancy_music_01.mp3`
`/content/sounds/music/fancy_music_12.mp3`
2. In `/content/soundevents/` create a new `.vsndevts` file
eg `/content/soundevents/music/fancy_music.vsndevts`
3. `.vsndevts` are KV3 files so you need to add the following at the top of every file
```
<!-- kv3 encoding:text:version{e21c7f3c-8a33-41c5-9977-a76d3a32aa0d} format:generic:version{7412167c-06e9-4698-aff2-e63eb59037e7} -->
```
4. Then put all your sound event definitions in `{}`
5. A sound event definitions looks like this:
```
Fancy.Music.Name = {
    type = "dota_update_default"
    vsnd_files = [
      "sounds/music/fancy_music_01.vsnd"
    ]
    volume = "1.000000"
    pitch_rand_min = "-0.050000"
    pitch_rand_max = "0.050000"
    pitch = "1.000000"
    soundlevel = "100.000000"
    spread_radius = "1000.000000"
    volume_fade_out = "0.200000"
}
```
`type` can be `"dota_update_default"` or `"dota_src1_3d"`. The latter seems to be used for moving sounds. There are more types but you probably won't need them.
`vsnd_files` contains a list of your sounds. Remember to change the file extension from whatever you have to `.vsnd`. Dota compiles every sound file to `vsnd`
For more keys take a look [here](https://github.com/SteamDatabase/GameTracking-Dota2/tree/master/game/dota/pak01_dir/soundevents)
Our [`charger.vsndevts`](https://github.com/OpenAngelArena/oaa/blob/master/content/soundevents/bosses/charger.vsndevts)

**Comment by ProstoSanja** [comment]
It was very hard to get needed type, and actually the right one was `src1_2d`
gonna write instruction now, for music people

**Comment by ProstoSanja** [comment]
Guide for our music people:
1) import your `mp3` or `waw` file to `content/sounds/music`
2) add it into `content/soundevents/music/music.vsndevts` by just copying existing one there and changing `root name` and `vsnd_files` (root is reference, by which code calls a file, and vsnd_files is its relative location)
2) open `music_list.lua` and fill in the new `root name, beautiful name and author`
3) use `Music:SetMusic(i)` where `i` is a number from  `music_list.lua` this function works globally

**Comment by warpdragon** [comment]
No i think we have to do this. The music people may not be proficient in git. In fact im almost certain theyre not.

**Comment by warpdragon** [comment]
Just find out where theyre keeping their source mp3s and grab them. Ryan will know this. It could just be the soundcloud im not sure

**Comment by ProstoSanja** [comment]
Okay, ill ask them to send music to me, so i can prepare everything here and then we test it and make one big pull

**Comment by Chronophylos** [comment]
Remember to disable the Debug for the module if you don't need it anymore

**Comment by ProstoSanja** [comment]
sure ill d that before pulling

**Comment by ProstoSanja** [comment]
Tested everything,works.
principle:
`playbackround` = playing any of background themes , which are in list between `start and stop`
`playmusic` = play any specific song like duel_prepare, duel etc based on list number
`finishmatch` = play win song for winnners, lose for losers.

**Pull request merged**
