### PR TITLE
Fixed Siege Mode becoming unusuable if you die while its active

### PR DESCRIPTION
**Pull request by SquawkyArctangent**
very complicated stuff here

### CODE REVIEW

**Comment by chrisinajar** [comment]
Should you set self.mod to nil if it's isNull?

**Comment by SquawkyArctangent** [comment]
Yes, because IsNull doesn't check if it's nil, but rather if the object doesn't exist any more.

Basically, it's a check to see if a pointer points to a dead object, rather a check to see if ... well, the variable isn't anything.

**Comment by chrisinajar** [comment]
Ah, i didn't expand the code to see the `else` block, i was saying it should be nil'd out so that the other code would recreate it. Looks good :+1:

**Comment by Haganeko** [comment]
Conflicts D=

**Comment by Chronophylos** [comment]
I resolved your nonexisting conflicts

**Pull request merged**
