### PR TITLE
Graphical Minimap

### PR DESCRIPTION
**Pull request by Satsaa**
This changes the minimaps. Main map is 1024x while the others are 512x to save space (small difference in-game in sharpness). Heavily inspired by Dota's minimap. I plan to update the minimap asap when a relevant pull is merged. Eg "More map fun #2319".
comparison

### CODE REVIEW

**Comment by l34Um1** [comment]
sick

**Comment by chrisinajar** [comment]
Kreygasm

**Comment by warpdragon** [comment]
How? Seriously this is amazing

**Comment by warpdragon** [comment]
U can merge my other PR btw im not workin on it

**Comment by Satsaa** [comment]
Thanks. I updated the main minimap to match Warp's pr. And for how, it's just the usual stuff and Krita's brush engines being great.

**Comment by chrisinajar** [comment]
LUL i remember when Krita was open source trash no one would use, like 8+ years ago xD

Waiting to merge this because the file names are all about to change with ranked mode, i can copy the files to the correct names then..

**Comment by chrisinajar** [comment]
added manually since map names changed

**Pull request closed without merging**
