### PR TITLE
9 new Items

### PR DESCRIPTION
**Pull request by imaGecko**
Putting the first batch out for review
My first new items I ever done, pls don't hurt me

Items included in the PR
Echo Sabre 5
Force Staff 1-5
Heavens Halberd 4-5
Lotus Orb 3-5
Magic Wand 1-5
Manta Style 5
Mask of Madness 4-5
Mekansm 1-5
Pipe of Insight 3-5

### CODE REVIEW

**Comment by warpdragon** [comment]
Dem icons need pips

**Comment by imaGecko** [comment]
I'll do all the icons at the end when everything else is done

**Comment by Haganeko** [comment]
Might leave a comment warning that over two images doesn't work for now.

**Comment by Haganeko** [comment]
So far as I know, Manta 4 is still plagued by the "can't spawn more than two illusions" bug. Might as well leave a note, especially if we're now promising four instead of just three.

**Comment by allanvbhg** [comment]
Maybe try and make it have 2 charges that both restore when it goes of cd.

**Comment by Haganeko** [comment]
If we're rewriting the item in lua, might as well just fix it.

**Comment by imaGecko** [comment]
manta will for now just say 2 illusions until it gets  a custom active

**Comment by imaGecko** [comment]
Items included in the PR
Echo Sabre
Force Staff
Heavens Halberd
Lotus Orb
Magic Wand
Manta Style
Mask of Madness
Mekansm
Pipe of Insight

I would put further items into a new PR

**Comment by imaGecko** [comment]
The conflict uses the new icons that are currently in the oaa repo, how would I solve that?

**Comment by Chronophylos** [comment]
The PR uses the same icons as in `OpenAngelArena/master`?
Is that what you mean?

**Comment by imaGecko** [comment]
yes, that's what I meant.

**Comment by Chronophylos** [comment]
run `git checkout game/resource/flash3/images/items/custom/manta_style_1.png upstream/master` to use the file from `upstream/master`

**Comment by imaGecko** [comment]
Or to clarify, I updated the pips. So it went from old icons to edited new icons. So the icons in the PR should override what's in OpenAngelArena/master

**Comment by Chronophylos** [comment]
run `git rebase`

**Pull request merged**
