### PR TITLE
Map - Cave Pathways

### PR DESCRIPTION
**Pull request by warpdragon**
redid the terrain for caves. awaiting proper gate functionality. do not merge yet. @Chronophylos can you please see the following:
1. Doors open when they're supposed to, but you can walk through some gates even when they are closed.
2. When you walk up to the Orange Box at the furthest Radiant cave, you get teleported to outerspace!

Thanks! WIP for now. Please Chrono take a look or someone who knows the blocker/gate code.

### CODE REVIEW

**Comment by warpdragon** [comment]
Also, the path between the first boss pit and the back "corridor" need to be removed (thanks to Allan for spotting this). Someone can fix this and PR to me, or I can fix it.

**Comment by warpdragon** [comment]
Also the big orange box preventing enemies from stealing rosh may need to be adjusted to match with the way the pathing does/doesn't work now that the map is more "open" in addition to the new anti-camping aura stills need to be implemented.

**Comment by allanvbhg** [comment]
Im working on the map rn, what does the orange box need to cover?

**Comment by allanvbhg** [comment]
because i think it still covers all the possible entrances etc

**Comment by warpdragon** [comment]
@allanvbhg you are not needed. the job is for coding... are you a coder?

**Comment by allanvbhg** [comment]
nope XD

**Comment by Chronophylos** [comment]
Which gates can you phase through?
Furthest Cave? Do you mean Room 4 of the Radiant Cave?

**Comment by warpdragon** [comment]
I've taken another look at fixing this thing. It NEEDS a coder to look at it. The way the map has to work involves team specific zone control. Right now the zone control for the farming cave has no such team differentiation.

**Comment by warpdragon** [comment]
Yeah no, @chrisinajar this is not something i can do. The fundamental "zone" mechanic was designed to:
1 keep players out of an area
2 teleport players out of that same area
3 use a door to illustrate visually when players can enter a room.
Those have now changed to:
1 keep players from crossing a threshold
2 teleport players out of an area
3 use a door to illustrate visually when players can enter/leave a room.

These are all important details that cannot be adequately captured with only map editing. I have spent 3 hours of fiddling just to figure out that I am not equipped to handle this. I require a coder, probably @Chronophylos to contribute to this PR before it can be merged. 

This map cannot be made playable without significant changes to the code. I will certainly apply further map changes once a coder has applied the functionality I require.

**Comment by Chronophylos** [comment]
The zone could be move on top of the gate. This means the zone unlocks and the gate opens. That's what you want, right?

**Comment by warpdragon** [comment]
cave_<team>_door_# should be 1-3, opening upon the completion of:
cave_<team>_room_# 1-3 (room 4 resets the cave)
cave_<team>_zone_#1-3 should get shrunk down to the same size as the doors, and used as "thresholds" similar to blink blockers
also what happens when the roshans die? if the doors close shouldn't players be teleported anyway?

**Comment by Chronophylos** [comment]
I can remove the TP in this PR

**Comment by Chronophylos** [comment]
Oh god. Warp.

**Comment by warpdragon** [comment]
What?

**Comment by warpdragon** [comment]
Did i do bad?

**Comment by Chronophylos** [comment]
All of your merging added some more commits
You weren't on a clean branch

**Pull request closed without merging**
