### PR TITLE
Make Cave consider four minutes clear

### PR DESCRIPTION
**Pull request by Haganeko**
As opposed to the previous eight.

### CODE REVIEW

**Comment by chrisinajar** [comment]
Doesn't this make cave slower? That'd be bad for the balance of it since then a hero can more likely farm it indefinitely..

**Comment by Haganeko** [comment]
It essentially means you'll need to clear it twice for the same reward as clearing once now. Difficulty will also grow at half rate.

**Comment by Melongod** [comment]
I'm not sure if we want people to have to dedicate more time to farming the cave while it's as boring as it currently is.

**Comment by Haganeko** [comment]
Clearly not going in.

**Comment by chrisinajar** [comment]
I think at this point we should base the models on the cave rather than vice versa. If we can define specific problems with the cave then we can discuss solutions to them, but I think unless a change is fixing a specific problem then we should wait until after the tournament.

Should we get a staging branch for 3.0 for changes like this?

**Comment by Haganeko** [comment]
Sure? I won't really be able to really do any real work until the tournament is over, though, and getting the rest of gold right (more early, less late) is my first priority.

**Pull request closed without merging**
