### PR TITLE
Abysall blade nerf made bash duration and active stun scale.

### PR DESCRIPTION
**Pull request by DerpySoccerBall**
Abyssal blade seemed a little too strong.

### CODE REVIEW

**Comment by imaGecko** [comment]
could have put in some scaling

**Comment by DerpySoccerBall** [comment]
It didn't scale normally, I just changed the numbers they are all the same don't know why it failed.

**Comment by imaGecko** [comment]
"it didn't scale normally" it's an item, it doesn't scale inanything normally because it doesn't have tiers in vanilla.
It fails because you didn't put //OAA behind custom values

**Comment by warpdragon** [comment]
Damn Derps put it down for em

**Comment by DerpySoccerBall** [comment]
what did I do that is making it fail the check now?

**Comment by warpdragon** [comment]
It's in the Travis details, Derp

```
------------------------------------ Fails -------------------------------------
# /home/travis/build/OpenAngelArena/oaa/game/scripts/npc/items/item_abyssal_blade.txt
  ✖ bash_duration should inherit basic dota values (1.5 vs 1.1)
    operator: equal
    expected: '1.1'
    actual:   '1.5'
    at: <anonymous> (/home/travis/build/OpenAngelArena/oaa/scripts/test/special-values.test.js:382:11)
    stack: |-
             Error: bash_duration should inherit basic dota values (1.5 vs 1.1)
             at Test.assert [as _assert] (/home/travis/build/OpenAngelArena/oaa/node_modules/tape/lib/test.js:224:54)
             at Test.bound [as _assert] (/home/travis/build/OpenAngelArena/oaa/node_modules/tape/lib/test.js:76:32)
             at Test.equal (/home/travis/build/OpenAngelArena/oaa/node_modules/tape/lib/test.js:384:10)
             at Test.bound [as equal] (/home/travis/build/OpenAngelArena/oaa/node_modules/tape/lib/test.js:76:32)
             at /home/travis/build/OpenAngelArena/oaa/scripts/test/special-values.test.js:382:11
             at Array.forEach (native)
             at testSpecialValues (/home/travis/build/OpenAngelArena/oaa/scripts/test/special-values.test.js:326:10)
             at testKVItem (/home/travis/build/OpenAngelArena/oaa/scripts/test/special-values.test.js:244:7)
             at /home/travis/build/OpenAngelArena/oaa/node_modules/ap/index.js:7:19
             at Array.forEach (native)
             
  ✖ stun_duration should inherit basic dota values (2.0 vs 1.6)
    operator: equal
    expected: '1.6'
    actual:   '2.0'
    at: <anonymous> (/home/travis/build/OpenAngelArena/oaa/scripts/test/special-values.test.js:382:11)
    stack: |-
             Error: stun_duration should inherit basic dota values (2.0 vs 1.6)
             at Test.assert [as _assert] (/home/travis/build/OpenAngelArena/oaa/node_modules/tape/lib/test.js:224:54)
             at Test.bound [as _assert] (/home/travis/build/OpenAngelArena/oaa/node_modules/tape/lib/test.js:76:32)
             at Test.equal (/home/travis/build/OpenAngelArena/oaa/node_modules/tape/lib/test.js:384:10)
             at Test.bound [as equal] (/home/travis/build/OpenAngelArena/oaa/node_modules/tape/lib/test.js:76:32)
             at /home/travis/build/OpenAngelArena/oaa/scripts/test/special-values.test.js:382:11
             at Array.forEach (native)
             at testSpecialValues (/home/travis/build/OpenAngelArena/oaa/scripts/test/special-values.test.js:326:10)
             at testKVItem (/home/travis/build/OpenAngelArena/oaa/scripts/test/special-values.test.js:244:7)
             at /home/travis/build/OpenAngelArena/oaa/node_modules/ap/index.js:7:19
             at Array.forEach (native)
```

**Comment by warpdragon** [comment]
You can do it

**Pull request closed without merging**
