### PR TITLE
Spirit Breaker and Dark Willow Nerfs

### PR DESCRIPTION
**Pull request by POCKETMONEY99**
Nerfed Spirit Breaker Greater Bash slightly at OAA levels. 

Reduced the spell amp talent for dark willow slightly. 
Increased cooldown on Shadow Realm, the hero was virtually unkillable with a octarine core and some defensive items. 
Rescaled terrorise cooldown to be lower at early levels but slightly higher at OAA levels.

### CODE REVIEW

**Comment by l34Um1** [comment]
@TheUnholyWrath does Willow need nerfs? She seems fine to me but you know better.

**Comment by DarkoniusXNG** [comment]
With Octarine Core, Dark Willow can have permanent Shadow Realm. Add Eul's Scepter on top of that and she is unkillable :D

**Comment by TheUnholyWrath** [comment]
not that much, the hero is "unkillable" if you have no aoe damage or have no way of getting her out of shadow realm, willow is incredibly squishy, into a zeus or a leshrac you just get completely melted. the other changes are good, if you desperately want to nerf shadow realm maybe 13 seconds, i dont think it needs nerfing that badly

**Comment by TheUnholyWrath** [comment]
> With Octarine Core, Dark Willow can have permanent Shadow Realm. Add Eul's Scepter on top of that and she is unkillable :D

its not permanent, late game a 5.5 second fear having a 14 second cooldown is something that deserves nerfing, shadow realm is really easy to counter if you pick a hero for it and theres a solid ~3 second downtime where you can just hex/silence/stun to your hearts content

**Comment by POCKETMONEY99** [comment]
I changed the cooldown back to 12 seconds at OAA levels. Exp Changes have helped out willow alot and Terrorize should be a once per fight spell, at 20 seconds cooldown you can get this off twice in a fight with octarine core.

**Pull request closed without merging**
