### PR TITLE
Update item drop table

### PR DESCRIPTION
**Pull request by Rachol**
Removed bottle drop.

Items are dropped about every 3rd creep. 

When it drops, it drops with following rate: 
-clarity with 25.7% rate
-tango with 64.3% rate
-mango with 10% rate

### CODE REVIEW

**Comment by chrisinajar** [comment]
i don't know if i'm ready to get rid of bottles, i've grown very attached

**Comment by Rachol** [comment]
:)

There are plenty of problems with bottles currently:
*They start dropping after 130 seconds.
*They make all the gpm calculations by Haganeko go to thrash, so we can't really see the real thing, how the power levels and so on develop.... GPM is through the roof because of them in the early game.
*Creeps are super weak because of them

**Comment by Rachol** [comment]
It would be also interesting if removing that, would make Baumi reconsider drops being a thing...

**Comment by Chronophylos** [comment]
We could make special bottles that can't be selled.-

**Comment by RamonNZ** [comment]
If there absolutely have to be bottles make them very unlikely to drop... watching the stream it is ridiculous. Like seriously.

**Comment by VoidsKeeper** [comment]
Make 6 bottles be crafted into portable-weaker-type-Shrines. You just place them and they heal your team for a certain amount. Maybe also make these "heals" not stack. That at least would give some meaning for the supports to collect them.
Or maybe allow three bottles combine into something (upgraded bottle?) that then can be combined into the portable shrine  (3 upgraded bottles become the Shrine ). 
Or any other variation of this... (I'm sure there's better ways to do it , but just thought this would be of use to supports)

**Comment by chrisinajar** [comment]
🎼I'm in love with a bottle 🎶

**Pull request closed without merging**
