### PR TITLE
Underlord Buffs

### PR DESCRIPTION
**Pull request by POCKETMONEY99**
Changed the level 25 talent from +25% spell amp to +200% Crit with 30% chance. The crit talent has better synergy with his other talents, aura support underlord will want the extra CC on pit and carry underlord will want the extra damage. Spell amp doesnt affect underlords Q max HP damage so +25% spell amp isn't very good. 

Improved some of Underlords other talents. 
Level 10: +70 Wave Damage or +40 Movespeed
Level 20: +100 Attack Speed or +50 Health Regeneration

Inncreased damage on firestorm at level 6. 

Decreased the mana cost on pit of malice at OAA levels. This spell doesn't really scale after level 4 so the large mana cost increase makes little sense.

### CODE REVIEW

**Comment by TheUnholyWrath** [comment]
you're kidding right? underlord ult isnt useable?

**Comment by warpdragon** [comment]
i mean, if we make a new map none of this balance is going to matter

**Comment by POCKETMONEY99** [comment]
> 
> 
> you're kidding right? underlord ult isnt useable?

This ultimate isnt unsuable. Enemies being able to jump through the portal is my issue. I feel like when you put this down in a teamfight it just causes chaos rather then being used for an actual purpose. You can also use it to get to the back line in teamfights but why do enemies need to be able to go through it? 

Outside of using the ultimate to teleport enemies into fountain (you can't do this anymore) there is no reason for **you** to want enemies to jump through the portal. Enemies can just move off the portal if they want to. 

If you want to forcefully displace enemies there are heroes which do it more effectively (fear heroes, venge swap, magnus skewer, flaming lasso, meat hook etc).

**Comment by TheUnholyWrath** [comment]
it ranges half the map and forces the enemy team to get off capture points while also potentially teleporting your entire team there. it just gets objectively worse for this use because they don't have to get off. its an awful duel spell, thinking of it as a duel spell is a mistake

**Comment by DarkoniusXNG** [comment]
Can you revert ult changes? I want to rework ult to be like Wormhole on this hero: https://hon.gamepedia.com/Riftwalker

**Comment by DarkoniusXNG** [comment]
Keep in mind that Superior Magic means it pierces BKB.

**Comment by POCKETMONEY99** [comment]
> 
> 
> Can you revert ult changes? I want to rework ult to be like Wormhole on this hero: https://hon.gamepedia.com/Riftwalker

Looks good.

**Comment by lovesmuffins** [comment]
I disagree with crit talent and would rather get a straight up damage talent for him. Something similar to Tide's level 25 talent.

**Comment by lovesmuffins** [comment]
ok can u atleast buff perma dmg to like 10 (talent)

**Comment by POCKETMONEY99** [comment]
> 
> 
> ok can u atleast buff perma dmg to like 10 (talent)

I want to see how these changes look first. I initally had buffed the bonus damage to +10 but at OAA levels this hero could easily be getting (20+10)*5=150 permanent damage after every teamfight. This is in addition to the temporary damage he will get from hero kills. This hero will be hitting exceptionally hard.

**Comment by lovesmuffins** [comment]
> > ok can u atleast buff perma dmg to like 10 (talent)
> 
> I want to see how these changes look first. I initally had buffed the bonus damage to +10 but at OAA levels this hero could easily be getting (20+10)*5=150 permanent damage after every teamfight. This is in addition to the temporary damage he will get from hero kills. This hero will be hitting exceptionally hard.

ye and thats fine with me cuz right now he serves no other purpose.

**Comment by DarkoniusXNG** [comment]
Bonus attack damage is something this hero doesnt really need. He gains so much permanent dmg just by existing in duels when heroes die near him. Crit dmg is fine.

**Pull request merged**
