### PR TITLE
Add devastator item 

### PR DESCRIPTION
**Pull request by adalessa**
base on the issue https://github.com/OpenAngelArena/oaa/issues/1586

Work Done:
- Create KV file for item_devastator (todo add the updages and put the correct values)
- Create Mock Icon for the image (need to be replaced, and add the upgraded ones)
- Create Mock for speel icon (Need to be replaced, and check if is need new one for each effect)
- Add devastator item KV file to npc item file
- Create devastator lua script
- Create effect for devastator, movespeed slow, and minus armor
- Replicate effect of desolator
-- Apply the corruption on hit check if is lower than the devastator does not applied it.
-- Add the base damage ( check that in game is directly added to the base damage, is not being displayed in green as other values added by items, not sure why is that)

Not Done
-- Item text, description

First time working on lua, any suggestion and correction more than welcome

Regards,
Aruk

### CODE REVIEW

**Comment by adalessa** [comment]
screen shot 2018-01-29 at 16 30 28
No test failed but still the build had error, any idea what I am doing wrong ? 

Thanks

**Comment by warpdragon** [comment]
U need an icon?

**Comment by warpdragon** [comment]
The build error often fails b/c of KV unrelated to anything u did. Its frustrating... u just have to wait and rebase on the next patch sometimes

**Comment by bcbails** [comment]
It looks like there were 15 warnings from luacheck at the top of the travis run. That may be your issue also.

**Comment by warpdragon** [comment]
ok so the fix is in. just ```git fetch upstream
git rebase upstream master```

**Comment by adalessa** [comment]
@warpdragon yes I need an Icon. I am with access to the computer where I have the code right now tomorrow I will do it. Thanks

**Comment by warpdragon** [comment]
concept

**Comment by l34Um1** [comment]
I think like a sword beam kinda thing works better. a sword crashing into the ground and a red sword like beam coming out of it.

**Comment by l34Um1** [comment]
Something like this https://www.youtube.com/watch?v=ecORhYhBktw

**Comment by carlosrpg** [comment]
I agree, a a morningstar would fit better with the effect of crushing armor

**Comment by l34Um1** [comment]
Ye but this is a beam. Your current icon doesn't show the beam at all. We can have the morning star with a beam?

**Comment by carlosrpg** [comment]
@adalessa What editor do you use? there is some whitespaces in the code that would be fixed if you used our editorconfig file

**Comment by warpdragon** [comment]
Ok i see. Ya something w a beam

**Comment by warpdragon** [comment]
concept2

**Comment by Haganeko** [comment]
If it's a Morningstar we have to call it Lucifer something. We just have to.

**Comment by warpdragon** [comment]
well the problem is that lucifer is the deceiver. but this item is the devastator. those are two distinctly different action verbs. deception is more about stealth, devastation is what this item is all about

**Comment by Haganeko** [comment]
Lucifer is also the Morning Star though.

**Comment by warpdragon** [comment]
I'm sure someone will come up with a dumb name. We're great at giving things dumb name *cough* covfefe *cough*

**Comment by Haganeko** [comment]
But we have an angel and demon theme, we have a Morningstar, and we don't name it after the fallen angel called the Morning Star?

**Comment by warpdragon** [comment]
Taste the rainbow bitch

**Comment by Haganeko** [comment]
Huh?

**Comment by warpdragon** [comment]
flavor pun

**Comment by carlosrpg** [comment]
Also, I was doing particles and saw that we have many items if color purple/violet I liked that the beam is going more to the yellow

**Comment by warpdragon** [comment]
Yes. Valve hates yellow. Let's use the crap out of it

**Comment by l34Um1** [comment]
but desos color is red. use yellow for something else

**Comment by Haganeko** [comment]
Well, this is technically not deso.

**Comment by l34Um1** [comment]
but it branches from deso, deso family

**Comment by warpdragon** [comment]
i mean you showed me a video with a beam and I just made it the same color as that. here's a red version
red

**Comment by l34Um1** [comment]
nice looks great

**Comment by adalessa** [comment]
> @adalessa What editor do you use? there is some whitespaces in the code that would be fixed if you used our editorconfig file

I am using visual estudio code. I have added an extensions to pick up the configuration.

I have added the icon thanks @warpdragon it looks great.

Still pending the particle effect still using the lina's one. sound effect if necessary and balance on the KV file.

Thanks everyone

Again any comments on the code more than welcome to improve it

**Comment by warpdragon** [comment]
There need to be 3 items, Desolator (tier 3), Desolator_2 (tier 4), and Desolator_3 (tier 5).
tier 3
tier 4
tier 5

**Comment by adalessa** [comment]
@warpdragon do you mean devastator correct ? I will add them

**Comment by warpdragon** [comment]
ya

**Comment by adalessa** [comment]
I have updated the files with the icons for the tier. I still have the issue when you equip the item the damage of it it goes directly to the base value istead of going to right of it as other items. The value applies correctly but it has that visual problem

**Comment by Haganeko** [comment]
That means you're adding base damage.

**Comment by adalessa** [comment]
I am ussing the modifier MODIFIER_PROPERTY_BASEATTACK_BONUSDAMAGE I use as reference. 
https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Lua_Abilities_and_Modifiers#Lua_Modifiers
Which one should I be ussing ?

**Comment by Melongod** [comment]
You are adding base damage for sure. 
Just tested it.

**Comment by Trildar** [comment]
Should have chimed in about this earlier. Didn't realise nobody mentioned it. You want `MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE `

I need to find some time to give this a proper review at some point.

**Comment by chrisinajar** [comment]
tooltips are quite incomplete. this is super close to done, would love to see it wrapped up...

**Comment by adalessa** [comment]
Thanks @Trildar changing that made it. 
@chrisinajar Yes the tooltip no idea what to write if there is an special lore or what to put there. 
Also is missing the effect. I am currently using the lina dragon slave one. I have never create an effect so no idea how to make a new one for this

**Comment by warpdragon** [comment]
@adalessa Effects are SUPER fun to make. 

1. Create new particle. Give it the following:

    - Renderer (Sprite Renderer with a sprite defined)
    - Emitter (Emit Continuously)
    - Operator (Lifetime Decay - Removes particle after emission)
    - Initializer (Lifetime Random - Clamps particle lifetime between max/min values)
    - Any other Operators/Initializers. Initializers define the properties of the particle at creation. Operators define the behavior of the particle over its lifetime.

2. Save particle to ``/content/particles``

3. Update your ability to use the new particle.

4. Perform Testing Cycle (Some particle changes don't even require game restart. Some do.)

**Comment by chrisinajar** [comment]
@adalessa just don't fill in lore. Tooltips are purely mechanical except the _lore line, which is 100% optional.

**Comment by l34Um1** [comment]
Is this going to be finished? Or will someone else finish it?

**Comment by adalessa** [comment]
I will try to finish it

**Comment by adalessa** [comment]
I have rebase from upstream and now I am getting a couple of error on files not related to this change. Is someone checking that ?
Related to this, I have to admit my defeat on the particles, I tried to made one, but I was not able to show it in the game. @chrisinajar I will leave it to some one that knows what is doing and later check and try to learn. So far my understanding that's the only thing missing on the behavior detailed on the  issue.

**Comment by adalessa** [comment]
I was looking at the wrong place apparently. Thanks @Trildar

**Comment by adalessa** [comment]
I have done all I can for this, as I mentioned before from my point of view is missing the particles, maybe a sound, and some test to confirm that is the expected behavior.
Regards

**Comment by l34Um1** [comment]
Needs better particles and sounds and all that adalessa mentioned but other than that it works just fine. Tooltips are missing on my end though. Ready to merge imo.

**Pull request merged**
