### PR TITLE
Add KV entries for heroes with Gold or XP talents

### PR DESCRIPTION
**Pull request by Trildar**
Initial entries so that these talents can be changed later. Based on Haganeko's list in #design-discussion on Discord.

### CODE REVIEW

**Comment by Haganeko** [comment]
Still gotta add the heroes with respawn talents, I assume?

**Comment by Haganeko** [comment]
I have redone those talents as well

**Comment by Trildar** [comment]
Yeah. I haven't done those since I didn't have a list. There is some overlap though at least.

**Comment by Haganeko** [comment]
I updated the doc... should still be somewhere around the discord, but I can reupload it if necessary.

**Pull request merged**
