### PR TITLE
items

### PR DESCRIPTION
**Pull request by warpdragon**
adding up to lvl 5 upgrades to 
aether lens
ancient janggo of endurance
armlet
bfury
black_king_bar
blade_mail
blink
charge_bkb
crimson_guard
cyclone
diffusal blade
dragon lance

### CODE REVIEW

**Comment by Chronophylos** [comment]
You failed
> All checks have failed

**Comment by warpdragon** [comment]
what is that bullshit?

**Comment by Chronophylos** [comment]
AND PLEASE WRITE WTF YOU HAVE CHANGED

**Comment by warpdragon** [comment]
it's freaking out because of my lack of tooltips then?

**Comment by Chronophylos** [comment]
Maybe, Travis log is too long

**Comment by Chronophylos** [comment]
I'll check it myself

**Comment by Trildar** [comment]
Travis build log has gotten a little silly hasn't it? Is there a way we can make it not so ridiculously long?

**Comment by Chronophylos** [comment]
Not show positive results

**Comment by Chronophylos** [comment]
```
  can read list of items

    âœ” no error

    âœ– should be truthy
    -------------------
      operator: ok
      expected: true
      actual:   0
      at: proxy (/home/travis/build/OpenAngelArena/oaa/node_modules/after/index.js:19:13)

    0
```

**Comment by warpdragon** [comment]
just relax omg. it's buggin cuz no tooltips.

**Comment by Chronophylos** [comment]
But I have to write the changelog. And I don't want to scroll through all of this

**Comment by warpdragon** [comment]
stop worryin bb. i'll cover everything next commit. i just got lazy.

**Comment by Chronophylos** [comment]
lazy

**Pull request merged**
