### PR TITLE
They made a good point

### PR DESCRIPTION
**Pull request by l34Um1**
And I am a doofus for not seeing it earlier.

Nerfed Refresher Core.

### CODE REVIEW

**Comment by Haganeko** [comment]
What was the point made? Please share.

**Comment by Melongod** [comment]
I pointed out that long cooldowns on huge spells are completely pointless if the refresher core cooldown is shorter than them.

**Comment by Haganeko** [comment]
Melon, I love you.

**Comment by Akkaren** [comment]
To be fair, in original dota reincarnation and blackhole got a higher CD at lvl 1 then refresher. But yes, i believe these are the only ones.

**Pull request merged**
