### PR TITLE
Fancy Lazor

### PR DESCRIPTION
**Pull request by Chronophylos**

### CODE REVIEW

**Comment by chrisinajar** [comment]
rebase

**Comment by chrisinajar** [comment]
There's concern this will be laggy, on discord we discussed having a particle that emits this instead of producing a new particle every 0.1 seconds

**Comment by allanvbhg** [comment]
We should test both imo. See what looks cooler and what lags more.

**Comment by Chronophylos** [comment]
I will change this and the fountain attack to auras

**Pull request closed without merging**
