### PR TITLE
Reimplement Expanding Shield and Particles

### PR DESCRIPTION
**Pull request by KarmaticNeutral**

### CODE REVIEW

**Comment by warpdragon** [comment]
Yooo

**Comment by warpdragon** [comment]
What work does this branch need to work?

**Comment by KarmaticNeutral** [comment]
Removed the particle bits from here because I did it better in the spell rather than do it on the entity itself which makes way more sense

**Comment by warpdragon** [comment]
This is gonna conflict

**Comment by warpdragon** [comment]
How should we handle this? My latest pr adds code to modifier_shielder_shieldex.lua

**Comment by chrisinajar** [comment]
Is this still needed? It doesn't appear to conflict, I just don't know what it does...

**Comment by KarmaticNeutral** [comment]
We very much need this. Currently the shielded doesn't have phase control cause I'm an idiot. This fixes that.

**Pull request merged**
