### PR TITLE
Item description fix

### PR DESCRIPTION
**Pull request by Declow0**
Custom items description is empty

Issue (#268)

Seems it doesn't need anymore. https://github.com/OpenAngelArena/oaa/commit/63066580de35d2dee47e0643ddc30726fdbc33d8 fix this problem.

### CODE REVIEW

**Comment by chrisinajar** [comment]
@warpdragon can you review this change and give me a 👍 👎 ?

**Comment by Chronophylos** [comment]
Someone broke encoding again...

**Comment by warpdragon** [comment]
I'm sorry what am i reviewing? If you want me to test `` "DOTA_Tooltip_ability_item_refresher_core_Note0" "Spell Lifesteal does not work."`` I wont be around for the next 24-36 hours except on mobile, and since Github thinks it's a Binary file I can't even compare it.

**Comment by chrisinajar** [comment]
merge with upstream

**Pull request closed without merging**
