### PR TITLE
Rewrite Rearm in Lua and make it not refresh Reflex Items

### LINKED ISSUE #606: Disable Rearm on Reflex Items
Currently Tinker can rearm Reflex Items. He shouldn't be able to.

### PR DESCRIPTION
**Pull request by Trildar**
Closes #606

### CODE REVIEW

**Comment by Haganeko** [comment]
Ooh, it's rewritten? That means we get to play with it!

**Comment by chrisinajar** [comment]
Change the name of the ability. Overwriting built in abilities with the same name can cause random crashes (seen with both bottle and tiny grow)

**Comment by Trildar** [comment]
Mass Serpent Wards, Demonic Conversion, Call of the Wild, and Nature's Call all overwrite though. Guess those should be changed too? Should the IDs also be changed?

**Comment by Chronophylos** [comment]
I resolved the conflicts created by the now clean kv files

**Comment by chrisinajar** [comment]
I think it only causes random crashes when dota has special code that interacts with that item or ability, such as bottle's special sharing properties or *everything about tiny grow*. Those other abilities are probably fine, but it's a trivial change to make sure it doesn't happen with rearm, which i wouldn't be surprised to see special interactions with.

**Comment by Trildar** [comment]
Should be good to go.

**Comment by chrisinajar** [comment]
Should you also respect that IsRefreshable method or whatever it's called, or is that not desired?

**Comment by Trildar** [comment]
I'm not sure. Vanilla Rearm didn't seem to when I tested it before. Refresher Core probably should though.

**Pull request merged**
