### PR TITLE
Massive Icon and Item related formatting and naming fixes

### PR DESCRIPTION
**Pull request by Chronophylos**
* Added new Icons with Pips
* Removed Tabs and wrong Line Endings of Item KVs
* Fixed Indentation of Item KVs
* Fixed Item Icon Names
* Fixed Spellicons #826

### CODE REVIEW

**Comment by warpdragon** [comment]
Reopening ths?

**Comment by chrisinajar** [comment]
Conflicts with pull staff

**Comment by chrisinajar** [comment]
Don't mind me, just a 55k diff with shit like this in the history
image

**Comment by Chronophylos** [comment]
yeah gonna rerun clean-files.js

**Pull request merged**
