### PR TITLE
Fix urn of sorcery level 2-4

### PR DESCRIPTION
**Pull request by chrisinajar**
I know they're being removed but WHATEVER DAD

### CODE REVIEW

**Comment by Melongod** [comment]
plz no :C

**Comment by Haganeko** [comment]
Can we try balancing them first, before we commit to removing them? I've had a few people say it's one of their favorite items, although its numbers are bad.

**Comment by GymLeaderGiovanni** [comment]
Who would have this as a fav. It hasn’t worked until now.

**Comment by warpdragon** [comment]
image
Must be my dope ass icons

**Comment by chrisinajar** [comment]
I'm pretty sure Frej was the only person who even noticed this item didn't work.

**Comment by GymLeaderGiovanni** [comment]
If Frej is the only person who noticed it didn’t work it’s cause he’s the only person to ever buy it.

**Comment by Haganeko** [comment]
People who liked the concept?

**Pull request merged**
