### PR TITLE
YUGE CHANGE

### PR DESCRIPTION
**Pull request by Minnakht**
Exchanged the previous name and lore of the most expensive item in OAA
for new ones. They're the best name and lore made of the best words.
This has been the best trade deal in the history of trade deals, maybe
ever.

### CODE REVIEW

**Comment by Chronophylos** [comment]
Hahaha

**Comment by Trildar** [comment]
Are we ever going to make this item not a meme?

**Comment by Chronophylos** [comment]
No?

**Comment by Minnakht** [comment]
Only when the name of the item is required to be used in a sentence.

**Comment by Haganeko** [comment]
Despite the constant negative Trildar covfefe...

**Comment by Minnakht** [comment]
Personally I like how the lore is actually relevant now. The item's mechanics are that it applies a short-lasting debuff, so if you want it to stay on an enemy you need to keep hitting them (constant negative press) and it reduces healing.

**Comment by Minnakht** [comment]
"enhancement"

**Comment by Minnakht** [comment]
https://i.gyazo.com/15b1f9b028f680d672acf80ae74bbf17.png

**Pull request merged**
