### PR TITLE
Hopefully fix travis

### PR DESCRIPTION
**Pull request by Chronophylos**

### CODE REVIEW

**Comment by Chronophylos** [comment]
This should fix the errors during deploy

**Comment by Haganeko** [comment]
It's this also obsolete?

**Comment by chrisinajar** [comment]
This edits a broken script to still be broken.

Chrono, when you're trying to find stuff relative to yourself use
```js
var path = require('path');

// join takes any number of paths and puts the correct slashes in and normalizes the path
// __dirname is the full path to wherever *this* script is
var filePath = path.join(__dirname, '../../some/path/to/file');
```

**Comment by Chronophylos** [comment]
Ohh.
The `(os.)path.join` I know just puts `/` in between

**Pull request closed without merging**
