### PR TITLE
Rework Arcane Orb

### PR DESCRIPTION
**Pull request by Trildar**
Now does physical damage and can target Ancients.

Also now counts as cast on attack rather than on projectile impact. No idea why the vanilla one even does that. Especially since the note on the ability says it spends the mana before calculating damage.

Apparently the int steal in the vanilla also does some weird things with enemy mana rather than simply preserving percentage like most stat modifications. I couldn't figure out how to reuse the in-built modifiers though, as it seems to expect some table value for the int steal amount. So now the int reduction works like any other with respect to mana.

### CODE REVIEW

**Comment by Haganeko** [comment]
Isn't not targeting ancients part of how it works in vanilla? Also, was OD still overpowered?

**Comment by chrisinajar** [comment]
Is there a ticket associated with this? What's the reason for this change?

**Comment by Haganeko** [comment]
It was an old ticket we never implemented and closed once it became clear Silencer was really the only problematic one.

**Comment by Trildar** [comment]
Oh? Guess I should have asked first. Still though, is OD considered fine as is? I know there were some minor complaints about the fact that he struggles to do any damage to bosses since he can't use Arcane Orb on them.

**Comment by Haganeko** [comment]
Similar to how he can't do anything to buildings in Vanilla

**Pull request merged**
