### PR TITLE
Swiper Boss

### PR DESCRIPTION
**Pull request by Trufllehunt**
I believe this is everything ive done so far. 
Swiper Model and textures
Animations for model
will add icons later

### CODE REVIEW

**Comment by warpdragon** [comment]
someone throw this on a test client

**Comment by carlosrpg** [comment]
The smd are left over files or you use both fbx and smd for animations?
I'll do the code to integrate with the swiper and create a test client for us to play with him

**Comment by Trufllehunt** [comment]
only the .fbx files are animations. The smd was accidental upload

**Comment by carlosrpg** [comment]
You need to add the materials to this PR

**Pull request closed without merging**
