### PR TITLE
Make Sparks cheaper

### PR DESCRIPTION
**Pull request by POCKETMONEY99**
Reduced the reciepe cost of sparks from 600 to 25. Currently there is no variety in starting items because most of your gold is commited for your spark. (Also everyone starts off with a spark so the cost shouldn't be be so high.)

### CODE REVIEW

**Comment by Larenall** [comment]
Why they just cant be free, you buy them no matter what. By making so they cost money you decrease starting gold. If you want starting gold to be lower then just lower it 4head and makes spark free. This is very wierd to me. you = whoever made so spark recepie costs money.

**Comment by POCKETMONEY99** [comment]
> 
> 
> Why they just cant be free, you buy them no matter what. By making so they cost money you decrease starting gold. If you want starting gold to be lower then just lower it 4head and makes spark free. This is very wierd to me. you = whoever made so spark recepie costs money.

I set the cost to 25 gold now. I don't think reciepes can cost 0 gold. Reciepes which cost 0 gold means there is no reciepe. This is about as 'free' as sparks will get. (I could set the cost to 1 but I don't think that will change anything).

**Comment by Larenall** [comment]
> > Why they just cant be free, you buy them no matter what. By making so they cost money you decrease starting gold. If you want starting gold to be lower then just lower it 4head and makes spark free. This is very wierd to me. you = whoever made so spark recepie costs money.
> 
> I set the cost to 25 gold now. I don't think reciepes can cost 0 gold. Reciepes which cost 0 gold means there is no reciepe. This is about as 'free' as sparks will get. (I could set the cost to 1 but I don't think that will change anything).

Fair

**Comment by DarkoniusXNG** [comment]
Wouldn't be easier to increase starting gold instead of doing this?

**Comment by POCKETMONEY99** [comment]
> 
> 
> Wouldn't be easier to increase starting gold instead of doing this?

It probably was but I have done it now lol.

**Pull request merged**
