### PR TITLE
Pretty Map

### PR DESCRIPTION
**Pull request by warpdragon**

### CODE REVIEW

**Comment by warpdragon** [comment]
things!

**Comment by chrisinajar** [comment]
still WIP?

**Comment by warpdragon** [comment]
Hey yeah my PR is technically ready to go. the ward spots aren't in yet and there's some improvements that would take a while. But it's in good shape. It all depends on if you guys want it as is (the state it's currently in on the test client) or if i should keep working on it. I don't know how long it will take me to do the new models.

**Comment by l34Um1** [comment]
I say add it in and then you can add your further improvements later.

**Comment by warpdragon** [comment]
Go for it

**Comment by warpdragon** [comment]
give me 1 more moment i need to add a precache bloc kto the upgrade core npc files

**Comment by warpdragon** [comment]
ALL DONE

**Comment by warpdragon** [comment]
yay

**Pull request merged**
