### PR TITLE
Reworked Satanic Core

### PR DESCRIPTION
**Pull request by Haganeko**
Reduced hero spell lifesteal, increased normal lifesteal a bit.
Unholy Rage didn't work like normal Satanic's; fixed that.
Buffed Satanic lifesteal so it wouldn't lose.

### CODE REVIEW

**Comment by Minnakht** [comment]
chris - this adds a new abilityspecial value to Satanic Core to display a tooltip. You will very likely need to amend code to merge this.

**Comment by Haganeko** [comment]
Tooltip file was changed appropriately, to use the new value. Don't know how the lua will react, but the other value was not renamed.

**Comment by Minnakht** [comment]
welp, my early morning reading comprehension has failed. sorry, disregard me

**Comment by imaGecko** [comment]
Unholy creep lifesteal doesn't add up to 200

**Comment by imaGecko** [comment]
No, what I mean your changed kv values don't add up to 200
creep_lifesteal + creep_spellsteal_unholy

**Comment by Haganeko** [comment]
There was a field specifically for that? Must have missed it. Will fix when able.

**Comment by chrisinajar** [comment]
@Haganeko conflicts

**Pull request merged**
