### PR TITLE
necronomicon_7 icon 

### PR DESCRIPTION
**Pull request by Apisal**

### CODE REVIEW

**Comment by chrisinajar** [comment]
conflict, was this already taken care of? could you describe the change here?

**Comment by Apisal** [comment]
my fork is 1000+ commits behind, i will update it later

the 1st  2 commits me adding and removing the wrong icon 

the 3rd commit adding necronomicon_7 icon to game/resource/flash3/images/items/custom/necronomicon_7.png

**Comment by chrisinajar** [comment]
that's the file in conflict, so i would assume someone else already added it...

**Comment by chrisinajar** [comment]
It looks like this already did what you're trying to do:
https://github.com/OpenAngelArena/oaa/commit/d7954f627a64bea3da7108134e2a3896fdb7cfac
@imaGecko can you confirm?

**Comment by imaGecko** [comment]
I only added the missing level, I didn't add any new icon just repeated the previous last one

**Comment by chrisinajar** [comment]
cool, i'll merge this with the next patch then :+1:

**Comment by Apisal** [comment]
sry man, i am new to git and i am busy with other stuff
the icon at visual art help , bye now :|

**Pull request closed without merging**
