### PR TITLE
Added Items to shop

### PR DESCRIPTION
**Pull request by Chronophylos**
I created a file where dota reads which items to display in which category and shop. I some of our items. But because space is spare and not enough not all items a displayed correctly.
Image

### CODE REVIEW

**Comment by Haganeko** [comment]
Remove small items from the shop, for now? Not like anyone us going to be buying bracers.

**Comment by Chronophylos** [comment]
Yeah, but how do I sort it? I could put the cores to the left most column..

**Comment by Haganeko** [comment]
Can you display the basic reflex core? Then clicking it would display all its upgrades...

**Comment by Chronophylos** [comment]
Current Layout 
Basic Upgrades

**Comment by Haganeko** [comment]
Looks good to me.

**Pull request merged**
