### PR TITLE
Magma Mage Boss (WIP)

### PR DESCRIPTION
**Pull request by DarkoniusXNG**

### CODE REVIEW

**Comment by chrisinajar** [comment]
i assume this is still wip

**Comment by DarkoniusXNG** [comment]
After some testing I find this boss still unfinished and boring. 
Description of the boss: When attacked he spawns volcanoes in random places and attacks you with his ranged attacks. Volcano stuns on eruption, spawns a totem and lava starts coming out of the totem. Lava spreads around the totem. Lava does damage if you stand in it. You can't destroy the totem without standing in lava unless you have high attack range. If the boss is low on HP he starts moving towards lava to heal. Things left to do:
- [ ] Attack sound
- [ ] Volcano eruption sound 
- [ ] Lava burning sound
- [ ] Improve AI
- [ ] Precache particles
- [ ] Add him to the list of bosses that can spawn
- [ ] Come up with another ability for a boss 
- [ ] Decide how his stats should be

Ideas I have so far for new abilities are:
1) something like Melting Strike (Invoker spawn ability), ability that procs on attack or improves his attack - problem with this idea is that he is called Magma Mage, he is supposed to be a mage..., 
2) Meteor - like Invoker's Chaos Meteor but deals damage and knocks people on impact - problem with this idea is that Meteors are not super related with Magma :D

I also don't know what tier should this boss be. He feels like he is tier 3 but he has only 1 ability, That's why I want another ability. Maybe he was intended to be tier 2.

**Comment by warpdragon** [comment]
dont call it a meteor then. call it an eruption fragment

**Comment by lovesmuffins** [comment]
have an ability where he sets the boss arena on fire and for like 3 seconds and does like 12% pure dmg of hp

**Comment by warpdragon** [comment]
Magma Mage powers up and fires a rapid barrage of fireballs toward a nearby hero.

**Pull request closed without merging**
