### PR TITLE
Icons Additions and Fixes

### PR DESCRIPTION
**Pull request by imaGecko**
New Icons for Daedalus and Radiance
Fixed missing or wrong Icons for Skadi, Aether Lens, Shivas, Blade Mail, Martyrs Mail, Ring of Aquila, Dagon 5
Skadi and Stoneskin Armor now have correct Pips
Siege Mode has custom wip icons

### CODE REVIEW

**Comment by Chronophylos** [comment]
AHHH, why did you name the icons `_1`? I just changed that!
@warpdragon tell us how you want them to be called.'
And you didn't replace the files in `images/spellicons`

**Comment by KarmaticNeutral** [comment]
There has been a bug popping up the icons named without the _1 that makes them use a random upper tier image. (item_name uses item_name_X)

**Comment by imaGecko** [comment]
So that explains the missing icons
It caused an issue with ring of aquila showing the wrong icon despite the correct one having been named in the kv file. Adding _1 solved the issue

**Comment by Chronophylos** [comment]
Valve pls

**Comment by warpdragon** [comment]
if the lack of a "_1" causes bugs, then let's use them.

**Pull request merged**
