### PR TITLE
Create Fountain Laser particle

### PR DESCRIPTION
**Pull request by Trildar**
Essentially a continuous version of the TI6 Laguna Blade particle. Implementation of particle to come. Probably by Chrono since he's reworking the Fountain Laser ability.

### CODE REVIEW

**Comment by KarmaticNeutral** [comment]
is there something wrong with what we are currently using? I really like it

**Comment by Haganeko** [comment]
What we are currently using is a way more resource intensive version of what Trildar has made - essentially, the current version creates a particle every .1s, which is a bit taxing on the engine.

**Comment by Trildar** [comment]
It should look essentially the same. It's just that we are currently spawning the Laguna Blade particle every 0.1 seconds, which is unnecessary particle spam.

**Comment by KarmaticNeutral** [comment]
ah okay so an efficiency issue. Sounds good.

**Comment by Chronophylos** [comment]
Yaay Thank you!

**Comment by Chronophylos** [comment]
Probably should merge this as I merged it in my `better-better-foutain` branch which I'll create a PR from

**Pull request merged**
