### PR TITLE
Vengeful Spirit Buffs

### PR DESCRIPTION
**Pull request by POCKETMONEY99**
Venge isnt very good anymore after all the gameplay changes. The changes to her aghs affected this heroes viability. 

Increased magic missle damage talent. 
Increased Wave of Terror Damage at Level 6. 
Rescaled Nether Swap CD (Less levels 1-4, same at level 5). Nether swap cooldown will be good at this cooldown because you will have 2 charges for most fights without it being nearly impossible to deal with like it was at 10 sec cd + old octarine core.

### CODE REVIEW

**Comment by lovesmuffins** [comment]
close this and I will buff venge myself.

**Comment by POCKETMONEY99** [comment]
> 
> 
> close this and I will buff venge myself.

Cant u just tell me what you going to do and I will add it?

**Comment by lovesmuffins** [comment]
> > close this and I will buff venge myself.
> 
> Cant u just tell me what you going to do and I will add it?

If you remove the ult changes I will than merge my ult changes into this. Else just start with a new pull commit

**Comment by lovesmuffins** [comment]
> Nether Swap is finally a balanced spell after the cancer of 10 second cooldown what it was and you dare to mention it :). Also new Scepter isn't that bad, it has better AoE than QoP fear.
> For Wave of Terror I don't know who lied to you, but armor reduction wasn't changed for months (since last year even). We nerfed all armor items and all items that give agility (except Butterfly) so your statement is definitely false.
> If you wanna buff Vengeful you should buff her bad talents and buff her aura (which was overnerfed imo). Max said that her aura has a lot of potential but I don't see how with those numbers. But the illusion is great and makes Vengeful the best aura carrier.
> Terrible talents that could be changed:
> 
> * lvl 10 talent -1 Wave of Terror Armor change to -2 or -3.
> * lvl 15 talent +15 Agility change to +30 or +40.
> * lvl 20 talent +8 Vengeance Aura Attributes to +16.
> 
> P.S. her ult doesn't need buffs.

the only thing about her ult I'd change his the cast range. I honestly prefer if it was just what it was at level 3... at all levels, even oaa.

**Pull request merged**
