### PR TITLE
Fix Manta Style

### PR DESCRIPTION
**Pull request by Trildar**
So many changes... commit logs pretty much describe them all. Most notably fixes the extra illusion and lack of outgoing damage reduction or incoming damage amplification mentioned in #1221.

Creating illusions of most heroes this way seems to cause lag when they spawn. Alchemist was particularly laggy for me, while Jakiro and Io both had no noticeable lag at all. Not sure this is fixable unfortunately.

### CODE REVIEW

**Comment by Haganeko** [comment]
Wow. Trildar really is the anti Chrono...

**Comment by Trildar** [comment]
To be fair, most of it is a bunch of small stuff, just broken up into a lot of commits so that the messages can be meaningful.

**Comment by Chronophylos** [comment]
The reason for my stupid calculation it that I wanted to allow a theoretical infinite number of illusions

**Comment by Haganeko** [comment]
Wait; will this break if we decide to go up to five images for some reason?

**Comment by Trildar** [comment]
It won't break, but the illusions won't have a nice formation anymore. I don't really mind too much if we place them evenly in a circle, but making that circle 256 radius is kind of silly. It's far too spread out. Practically becomes like Doppelganger rather than Manta.

**Pull request merged**
