### PR TITLE
Recommended Item builds

### PR DESCRIPTION
**Pull request by DarkoniusXNG**

### CODE REVIEW

**Comment by POCKETMONEY99** [comment]
Made a merge request on this branch. My early game items need updating and hotd and drums need swaping around for heroes.

**Comment by DarkoniusXNG** [comment]
Can you not put max level items in guides? Put the first level that's available to buy.

**Comment by POCKETMONEY99** [comment]
> 
> 
> Can you not put max level items in guides? Put the first level that's available to buy.
Maxed out items are exactly what a late game items are. I removed maxed out items from luxury. 

For example with AA "item_glimmer_cape_2" "item_octarine_core" arent late game items. I will have glimmer and octarine core by 15 minutes latest. "glimmer_cape_5" and "octarine_core_5" are late game items. Thats just my thought process.

It also makes upgrading items more obvious. I have seen alot of players with lots of gold and lots of cores but only have tier 1 items in their inventory.

**Comment by DarkoniusXNG** [comment]
I changed most of bad item guides. I don't have a will do more of this. I will let others update guides using the template.

**Comment by POCKETMONEY99** [comment]
Sent a PR with the rest of the item builds

**Comment by DarkoniusXNG** [comment]
@POCKETMONEY99 We have a guide for every hero now?

**Comment by POCKETMONEY99** [comment]
> 
> 
> @POCKETMONEY99 We have a guide for every hero now?

Yes. Numbers match up (119 - 1 (meepo) + 2 (custom heroes) + 3 other files ) =123

**Pull request merged**
