### PR TITLE
Add Travis CI Image

### PR DESCRIPTION
**Pull request by Chronophylos**

### CODE REVIEW

**Comment by ProstoSanja** [comment]
The moment you try to add travis, and build fails before even adding :=

**Comment by Chronophylos** [comment]
Travis is not configured...

**Comment by warpdragon** [comment]
Can someone explain travis to me?

**Comment by Gabrielmtn** [comment]
@Chronophylos just a heads up you have a failing test I think

**Comment by Chronophylos** [comment]
We don't even have a .tavis.yml....

**Comment by Gabrielmtn** [comment]
Odd that the integration is active then, but now that I've checked other PRs I see the issue is everywhere. Thought it might be a sync issue

**Comment by Chronophylos** [comment]
The integration and creation/setup of Travis CI are two different things.

**Comment by Gabrielmtn** [comment]
Right of course, I didn't view the content of the check it's self, just thought you might not have seen it.

**Comment by chrisinajar** [comment]
I'm still in the middle of getting the travis integration to work, we have no tests yet but i'm working on getting our english strings auto-uploaded to the translation tool we're using.

Who wants to figure out lua test cases? :D :D  :D

**Comment by Chronophylos** [comment]
Won't there be problems with the C++ defined Lua functions?

**Pull request merged**
