### PR TITLE
Lifestealer Rage and Feast Nerf 

### PR DESCRIPTION
**Pull request by POCKETMONEY99**
Reduced the amount of attack speed rage gives at level 6. Also Made the rage duration not scale past level 4, meaning he can't reach more then 8 seconds of spell immunity. 

Additionally I left a hero file for lifestealer, if anybody wishes to change his talents or stats in the future. 

Additional Notes
Lifestealer counters need buffing, currently the only viable counter to lifestealer is Shadow Demon. The top lifestealer counters are Razor and Ursa.

I also nerfed rage cooldown to align with 7.19d

### CODE REVIEW

**Comment by DarkoniusXNG** [comment]
The problem with this is: People will never take the STR talent and they will always take the other talent (feast upgrade) which will further buff the broken thing on lifestealer.

**Comment by Haganeko** [comment]
Removing an option isn't a buff. People already have the option of picking the Feast talent.

**Comment by DarkoniusXNG** [comment]
Its a buff to late lategame lifestealer and a nerf to midgame lifestealer. He can have both (feast increase and rage duration increase) with these changes.

**Comment by Haganeko** [comment]
Then the issue is not the talent, but the increase in duration at later levels.

Well, that and the strength talent being supposedly so weak it'll never be picked.

**Comment by DarkoniusXNG** [comment]
I think this will solve the issue with Lifestealer:
1) Duration scaling should stay the same: 3/4/5/6/6.5/7
2) LVL 25 talent should stay the same but instead of +2 Rage duration -> +1s Rage duration

Also attack speed nerf at OAA levels seems reasonable.

**Comment by POCKETMONEY99** [comment]
> 
> 
> I think this will solve the issue with Lifestealer:
> 
>     1. Duration scaling should stay the same: 3/4/5/6/6.5/7
> 
>     2. LVL 25 talent should stay the same but instead of +2 Rage duration -> +1s Rage duration
> 
> 
> Also attack speed nerf at OAA levels seems reasonable.

**Comment by POCKETMONEY99** [comment]
> 
> 
> Reduced the amount of attack speed rage gives at level 6. Also Made the rage duration not scale past level 4, meaning he can't reach more then 8 seconds of spell immunity.
> 
> Additional Notes
> Lifestealer counters need buffing, currently the only viable counter to lifestealer is Shadow Demon. The top lifestealer counters are Razor and Ursa.

**Comment by POCKETMONEY99** [comment]
> 
> 
> I think this will solve the issue with Lifestealer:
> 
>     1. Duration scaling should stay the same: 3/4/5/6/6.5/7
> 
>     2. LVL 25 talent should stay the same but instead of +2 Rage duration -> +1s Rage duration
> 
> 
> Also attack speed nerf at OAA levels seems reasonable.

I nerfed rage so you don't have to change the talent anymore. I made rage duration at level 5 and 6 remain at 6 seconds. The attack speed bonus from rage is only less at level 6 now.

**Comment by DarkoniusXNG** [comment]
I am fine with this.

**Comment by DarkoniusXNG** [comment]
These changes are fine.

**Pull request merged**
