### PR TITLE
Map Enhancements etc

### PR DESCRIPTION
**Pull request by Satsaa**
Gameplay is overrated...
-Revised dire arena and swapped arenas
-Copied things from default map because they look nice
-More grass
-Texture fixes
-Made sure the main shopkeepers are different and assumed arena shopkeepers as twins
-Lifted area behind bosses where no one goes for vision advantage

vpk file size 29,795 -> 29,993 KB

-Removed background from music ui for clean look

Also the ranged twin should no longer heal when the melee is dead. Additionally allowed twins healths to differ a bit.

### CODE REVIEW

**Comment by Chronophylos** [comment]
Do you have some screenshots?

**Comment by Satsaa** [comment]
Ignore the map lul

**Comment by Chronophylos** [comment]
Is that our map? Looks awesome!

**Comment by l34Um1** [comment]
Please undo all gameplay related changes like the boss pits being low ground.

**Comment by Satsaa** [comment]
Oh the bosses are still at the same height its just the path behind them is highground, but i assume thats what you mean. 
3478f9d5b889bfb7b2dad521e331fbfc

**Comment by l34Um1** [comment]
Alright, nevermind then.

**Comment by Satsaa** [comment]
Okay. I have a version without highrounds if you change your mind then.

**Comment by warpdragon** [comment]
i'm ok with either. great job dude!

**Comment by chrisinajar** [comment]
oops, thought you already uploaded the one with the highground fixed. Sorry, can you open a new PR, i'm going to just revert it off master and merge in the one you're done with

**Pull request merged**
