### PR TITLE
Fix Fountain auto-doom

### PR DESCRIPTION
**Pull request by Trildar**
Should now perform its intended purpose of disabling passives on heroes hit by Fountain. Also gave Fountain True Strike.

P.S. We should discuss whether we want the Fountain to outright kill everything. Including through things like Borrowed Time and Ghost Scepter.

P.P.S. Woo! #1000!

### CODE REVIEW

**Comment by Chronophylos** [comment]
Why does the damn modifier work for you? It doesn't for me and I have roughly the same file.
Valve pls

**Comment by imaGecko** [comment]
nobody even commented that this was PR #1000

**Comment by Chronophylos** [comment]
> P.P.S. Woo! #1000!

**Comment by Haganeko** [comment]
> nobody even commented that this was PR #1000
Shame, Gecko.

**Pull request merged**
