### PR TITLE
bugfixes-and-nerfs

### PR DESCRIPTION
**Pull request by warpdragon**
still testing sigil.

### CODE REVIEW

**Comment by warpdragon** [comment]
created the units sigil5 and sigil6. added them with #base into npc_units_custom. Sigil still doesn't spawn at lvls 5 & 6.

**Comment by chrisinajar** [comment]
why nerf veno wards? They're strong, but not compared to probably 10 other heroes each a hundred times stronger....

i would get zues or huskar or enigma nerfs...... but veno?

**Comment by warpdragon** [comment]
I can revert it if you want. Just gotta figure out how to do that.

**Comment by Honeth** [comment]
Chris we can always change veno wards to be able to walk with 100 ms haha

**Comment by Chronophylos** [comment]
@warpdragon `git revert b7611ac`

**Comment by chrisinajar** [comment]
Awesome, I think we should be very conservative and data driven about balance changes, and virtually always discuss them in discord. It's easy to see something as broken without realizing that it's supposed to be :D 

Remove the WIP label when you're done with the tweaks :+1:

**Comment by warpdragon** [comment]
yeah i'm just adjusting the stuff baumi said was broken. veno was unnecessary.

**Comment by warpdragon** [comment]
u know what? i'm not even gonna touch Refresher Core. Like yall said it needs its active abillity. no point adjusting anything before then.

**Comment by warpdragon** [comment]
you can merge this. its beyond my LUA understanding to create a new "oaa_frozen_sigil.lua" but the addition of the sigil units will be required regardless.
also the changes to enigma will hopefully result in less of this:
image

**Pull request closed without merging**
