### PR TITLE
Nerf creeps for release

### PR DESCRIPTION
**Pull request by Haganeko**
Also undid front loaded XP and removed the player number XP factor.

### CODE REVIEW

**Comment by chrisinajar** [comment]
I assume that the new equations make up for the hugely nerfed exp?

**Comment by chrisinajar** [comment]
Also why undo frontloaded xp? isn't that a good thing? we just want the creeps to be easier to kill but otherwise unmodified. I could easily just add a..
```
if minute < 10 then
  armor = armor * (20 - minute) * 0.05
  damage = damage * (20 - minute) * 0.05
end
```

**Comment by Haganeko** [comment]
After minute six or so. The old version gave you a boatload of XP at minute 0 and kept it there for some time. This progresses earlier. But please do plot the expected values of 98, 123, 98 vs the old ones of 240, 360, 240.

**Comment by Haganeko** [comment]
Well, people are going to kill creeps way more easily. The old version lets you reach level 2 from clearing a single easy camp, once! This one will mean that for everyone to get their levels, they'll need to use everything they can, including the farming cave and the occasional kill.

**Comment by chrisinajar** [comment]
Seems legit, lets give it a shot! Test game anyone @here? :D

**Pull request merged**
