### PR TITLE
Make fountain target wards

### PR DESCRIPTION
**Pull request by Chronophylos**

### CODE REVIEW

**Comment by Trildar** [comment]
This doesn't seem to actually work for some reason.

**Comment by chrisinajar** [comment]
I bet `fountain_attack.lua` does it's own scan with hardcoded flags instead of using the getter... also damn you chrono, test your code :P

**Comment by Trildar** [comment]
I checked. The code should use the ability's flags. So I dunno.

**Comment by Trildar** [comment]
`DOTA_UNIT_TARGET_OTHER` is invalid in KV for some dumb reason. Fixed in #1686 by adding the target type in Lua instead.

**Pull request closed without merging**
