### PR TITLE
Sohei Arcana

### PR DESCRIPTION
**Pull request by warpdragon**
Reference

### CODE REVIEW

**Comment by warpdragon** [comment]
Sculpting 1

**Comment by warpdragon** [comment]
Color 1

**Comment by warpdragon** [comment]
Imported 1

**Comment by warpdragon** [comment]
merge plz

**Comment by chrisinajar** [comment]
R U REDY 2 RUMBLE!?!?!!?

**Comment by warpdragon** [comment]
ready enough

**Comment by chrisinajar** [comment]
do any of the abilities have special particles for the arcana? It'd be cool if at least during the ult he gained the SSJ effects or something.... just a passing thought

**Comment by warpdragon** [comment]
nope. just hte model

**Comment by warpdragon** [comment]
i think @carlosrpg has a particle for his base model. i'm sure it would be easy to add particles to some of his spells but i hadn't planned on doing any personally.

**Comment by chrisinajar** [comment]
How do you turn it on/off?

**Comment by chrisinajar** [comment]
modifier would be ideal, think you can add that in?

**Comment by carlosrpg** [comment]
Integrated on my PR #2302 . Including modifier to change the arcana and particles recolor

**Pull request closed without merging**
