### PR TITLE
Armor progression

### PR DESCRIPTION
**Pull request by Haganeko**
Once again, this time rebased to avoid conflicting with Chrono changing EVERYTHING EVER.
Will debate changes on the next town hall; do not merge for now.

### CODE REVIEW

**Comment by Chronophylos** [comment]
But the KV's are beautiful now

**Comment by Haganeko** [comment]
That is a fair point.

**Comment by imaGecko** [comment]
Time to slowly mess up the files again

**Comment by Chronophylos** [comment]
don't you dare

**Pull request closed without merging**
