### PR TITLE
Prevent Lazor Particle from Growing

### PR DESCRIPTION
**Pull request by Chronophylos**

### CODE REVIEW

**Comment by Trildar** [comment]
Pretty sure this actually affects the smoke. You probably want to look at messing around with `fountain_lazor_sphere`.

**Comment by Chronophylos** [comment]
In the particle editor the white sphere stopped growing

**Comment by Trildar** [comment]
Probably incidental. I just checked, and disabling that operator in the parent particle makes the smoke particles really tiny because they don't get their radius set. Try disabling the children particles if you want to check for yourself since the smoke can be hard to see with everything else going on.

**Comment by Chronophylos** [comment]
I'll look into it

**Pull request closed without merging**
