### PR TITLE
Balance

### PR DESCRIPTION
**Pull request by l34Um1**
rip haganeko when he sees the bosses

### CODE REVIEW

**Comment by Haganeko** [comment]
I'm actually okay with the magic resistance thing, though I'd probably have stuck to a more conservative 0.

**Comment by l34Um1** [comment]
I spent a long time thinking about it and I think -25% is better but I wouldn't be surprised if I am wrong. Luckily it's an easy fix if it needs to be changed again.

**Comment by Haganeko** [comment]
True. Getting a bunch more bosses where just right clicking away doesn't work should help!

**Comment by SquawkyArctangent** [comment]
Don't forget to change AbilityCastRange on the Underlord ult - there's a reason why the keyvalue has the "_tooltip" part at the end

**Pull request merged**
