### PR TITLE
Add script for automatic checking for updates on ability stats

### PR DESCRIPTION
**Pull request by onc**
This is a first WIP script for automatic update the ability KVs.

Issues left: 

- The kv file from https://github.com/dotabuff/d2vpkr is not valid.
there are two lines which should be a comment, but only contain one (instead of two) slashes. See my script header for details.

- The file https://github.com/OpenAngelArena/oaa/blob/master/game/scripts/npc/abilities/zuus_cloud.txt is also not valid, since it does not start with the usual `"DOTAAbilities" {` header.

Until now, this script only produces a diff, printed into the terminal. You can use it and pipe the output into a file. The content looks something like this at the moment:

```
=====================
 Diff for: abaddon_death_coil
=====================
[{"kind":"E","path":["AbilitySpecial","04","values","missile_speed"],"oaaStats":"2000","dotaStats":"1600"}]

=====================
 Diff for: alchemist_acid_spray
=====================
[{"kind":"E","path":["AbilitySpecial","01","values","radius"],"oaaStats":"625","dotaStats":"400 475 550 625"}]

=====================
 Diff for: alchemist_chemical_rage
=====================
[{"kind":"E","path":["values","AbilityCooldown"],"oaaStats":"45.0","dotaStats":"55.0"}]
```

I'm going to work on writing the changes into the KV files soon. I wan't to use this pull request for further discussions on how to do it best.
Maybe we wan't something like an interactive thing, which asks  if updates should be done, before writing them into the file. Or you could just run the script and check `git diff` afterwards.

### CODE REVIEW

**Comment by chrisinajar** [comment]
This is fucking awesome.

**Comment by warpdragon** [comment]
I love awesome things

**Comment by Haganeko** [comment]
Any updates on this? It's been sitting still for some time.

**Comment by onc** [comment]
Hey guys. I'm really sorry I couldn't finish this yet. I had a lot of stuff to do at university. I hope I can finish it this weekend.

**Comment by Haganeko** [comment]
It's okay. Just wanted to make sure you were still around.

**Comment by imaGecko** [comment]
I wonder how this will interact with abilities that have changed vanilla values as part of oaa balance

**Comment by Chronophylos** [comment]
we could make the script ignore those exceptions via a simple comment like `// ability-diff ignore`

**Comment by Haganeko** [comment]
Make the script throw a warning do we know what to look at by hand?

**Comment by chrisinajar** [comment]
Closing dead PRs

**Pull request closed without merging**
