### PR TITLE
Pips

### PR DESCRIPTION
**Pull request by hallelsegel**
just a quick pips pr

### CODE REVIEW

**Comment by imaGecko** [comment]
the pips are wrong. highest vanilla item should get 1/6 then 2/6 to 6/6 for the 5 farming upgrades

**Comment by KarmaticNeutral** [comment]
highest vanilla = 1/6
add Fcore = 2/6
add UC1 = 3/6
etc. Gecko is right

**Comment by Trildar** [comment]
You need to change the KVs in the files in `game/scripts/npc/items/farming`. They all currently point to the `custom/greater_arcanes`. Just change the value path after `AbilityTextureName`.

**Comment by hallelsegel** [comment]
change the first one to "_1" or leave it as it is?

**Comment by hallelsegel** [comment]
and where is regular arcanes?

**Comment by imaGecko** [comment]
https://github.com/dotabuff/d2vpkr/blob/master/dota/resource/flash3/images/items/arcane_boots.png

**Comment by Trildar** [comment]
Match the file name of the icon file. So if you put _1 for that, put it in the KV as well. We don't have a KV file for vanilla Arcane Boots, so just put the icon for it in `items` instead of `items/custom`. Should work.

**Comment by hallelsegel** [comment]
and the txt? all the other boots have files and arcanes don't as far as i can see

**Comment by hallelsegel** [comment]
ok i see thanks

**Comment by chrisinajar** [comment]
i'm already fixing the KV in my test case branch, just do the base arcanes

**Pull request merged**
