### PR TITLE
Balance

### PR DESCRIPTION
**Pull request by chrisinajar**

### CODE REVIEW

**Comment by DarkoniusXNG** [comment]
Travis working again?

**Comment by chrisinajar** [comment]
apparently? i didn't change anything

**Comment by lovesmuffins** [comment]
with the travel buffs does this mean my changes will still be put in or should I scale it back now.

**Comment by lovesmuffins** [comment]
some of these changes also interfere with shannon's proposed item changes. You pushed an update to arcanes rather than just pushing shannon's arcane buff (and their practically the same buff to gold)

**Pull request merged**
