### PR TITLE
Rebalance Boot Gold

### PR DESCRIPTION
**Pull request by Haganeko**
Let's try this. If they're overnerfed we can try something else
/Should I do the fools gold increase here too? Would be more thematic than in the middle of Baumi's balance patch.

### CODE REVIEW

**Comment by chrisinajar** [comment]
Wow, so fools gold is going down to 30% *and* the gold from boots is being reduced by over half? How are supports going to be able to afford anything? All the level 1's are reduced by well over half, and the level 2's are pretty close... It'll take supports well over double the amount of time to acquire their items. I was thinking like a 20-30% nerf and then a buff to travels...

**Comment by Haganeko** [comment]
This is experimental. I have another set of values ready to go depending on feedback.

**Comment by chrisinajar** [comment]
Lets save experiments for after the tournament.

**Comment by chrisinajar** [comment]
Perhaps we should start a branch for post-tournament to start merging stuff like this into it?

**Comment by Haganeko** [comment]
Are you really going to block something we discussed extensively in discord?

**Comment by chrisinajar** [comment]
Not block, merge into the correct branch. We shouldn't be making radical (reducing GPM by over half is definitely radical) changes right now. Anything you consider "experimental" should wait until after. We'll *massively* destabilize the meta right after the tournament and add in all kinds of crazy shit, but we shouldn't be tableflipping the meta leading up to the tournament.

**Comment by Haganeko** [comment]
There is a month till, and inscriptions are still open. Plus, this is just correcting an egregious balance oversight. This is the correct power level for the boots. The only question is whether all gold is wrong and needs to be increased.

**Comment by chrisinajar** [comment]
Define "correct", how are you measuring that?

**Comment by chrisinajar** [comment]
How can something be both "correct" and "experimental" with backup numbers ready to deploy in case they're wrong?..... I think maybe we need to rethink how we're measuring what these values need to be.

**Pull request merged**
