### PR TITLE
Lcyan Buffs

### PR DESCRIPTION
**Pull request by POCKETMONEY99**
Decreased cooldown of Shapeshift.

### CODE REVIEW

**Comment by Larenall** [comment]
Id also propes to give lycan and all his summos phase in Shapeshift, cuz killing bosses with 5 wolves + 2 necros is annoying cuz they block everybody and also cuz some location in oaa dont have much space for this amount of units

**Comment by POCKETMONEY99** [comment]
> 
> 
> Id also propose to give lycan and all his summos phase in Shapeshift, cuz killing bosses with 5 wolves + 2 necros is annoying cuz they block everybody and also cuz some location in oaa dont have much space for this amount of units

yeah I feel you, but I have no idea how to do that. I would ask Darkonious or something on how to do that. Ngl It would be nice for other heroes like Naga Siren too.

**Comment by lovesmuffins** [comment]
You'd have to remake the entire ability, so Larenall's idea isn't as cut and dry as it seems.

**Comment by DarkoniusXNG** [comment]
@lovesmuffins The shapeshift thing can be done with modifier filter.

**Pull request merged**
