### PR TITLE
Made a Bunch of Creeps Ancient

### PR DESCRIPTION
**Pull request by Haganeko**
Hard Camp and Farming Cave.
Should reduce Clinkz power a fair bit, and give some meaning to Chen aghs.
Marked WIP so Baumi can look at it before it gets merged.

### CODE REVIEW

**Comment by imaGecko** [comment]
The new creeps need names

**Comment by Haganeko** [comment]
Huh. Where do I add that? Tooltips? In any case, I don't even know whether this is going in or getting discarded.

**Comment by imaGecko** [comment]
https://github.com/OpenAngelArena/oaa/blob/master/game/resource/English/npc/npc_creeps.txt

**Comment by warpdragon** [comment]
Yeah just copy the tooltip data from other units and change it. The names wont show up in game unless u overwrite addon_english

**Comment by warpdragon** [comment]
If you DO edit addon english, revert to original b4 committing

**Comment by Haganeko** [comment]
Yeah, after Gecko Sen the link I recalled giving the Tomato Warrior a name.

**Comment by Haganeko** [comment]
I don't know what the problem is, now.

**Comment by chrisinajar** [comment]
`npc_dota_neutral_custom_giant_wolf is missing a title            - Add the key: "npc_dota_neutral_custom_giant_wolf"`

**Comment by TheObbyDragon** [comment]
Wouldn't that be a slight nerf to chen though? i wouldn't say hes very imba

**Comment by TheObbyDragon** [comment]
take a slot from him

**Comment by Haganeko** [comment]
Well, he'll have sole access to cave creeps, which were a valid strat for enchantress as far as I could tell

**Comment by chrisinajar** [comment]
That strat depended on a since-fixed bug. Also enchantresses talent for ancients doesn't work.

**Comment by Haganeko** [comment]
Well, farming cave creeps can still get very tough, so I think Chen can still benefit from them.

**Comment by chrisinajar** [comment]
coonnnfflliicctttssss @Haganeko

**Comment by Haganeko** [comment]
Back as WIP because accidentally undid part of the blueberry thing
Also Chris creep_types.lua has called for a nonexistent creep (fulborg instead of furbolg) for ages and nothing caught it.

**Comment by Haganeko** [comment]
Didn't create a file. Just undid undoing blueberry thing. Can be merged now.

**Pull request merged**
