### PR TITLE
Item tree Optimisation (Removed Backward Compatibility)

### PR DESCRIPTION
**Pull request by POCKETMONEY99**
***Items in this PR have had their backward compatibility with cores removed***

Based on Larnells issue and some other voices in the community. Generally I feel that grouping up items with simillar stats is the best way for items to be in an item tree. There are some other items that need adjusting but I am not sure why they are currently in their tree. 

**MKB/Mjolnir Tree** 
MKB and Mjolnir are now in the same tree. These items are fairly simillar so grouping them together makes sense. Additionally it allows you to switch your item around depending on if enemies have evasion or not. 

**Eye of Skadi Tree**
Echo Sabre is now in the eye of skadi tree (Still tier 2 item). I buffed its stats across the board as it needs to compare to eye of skadi, abyssal blade and Blade of Judecca. Abyssal blade is now a tier 2 item instead of tier 3. 

**Nullifer/Bloodthorn Tree**
Nullifier is now a tier 3 item and is part of the daedalus and bloodthorn free. Bloodthorn is now a tier 1 item and orchid 2 has been removed. Bloodthorn is easily dispellable and if you see a bloodthorn you can predict the doom build and buy a dispel orb or lotus orb etc. (Dispel orb hard counters this build). I moved nullifier from the echo sabre tree as its stats are vastly different to echo sabre (also echo sabre is part of the skadi tree and nullifier offers no HP or stats.)

**Satanic Tree**
Mask of Madness is now a tier 2 item. This item is extremely niche (only good on lone druid bear) so may need the strength that Satanic offers to prevent major stat loss. (If the item had bonus strength it wouldn't affect druid bear so thats a bonus). 

**Hurricane Pike Tree**
Dragon lance Upgrades have been removed and hurricane pike is now a tier 1 item. Currently going hurricane pike isn't viable because you have to go through level 2 dragon lance. (Same problem that yasha, kaya and sange 2 make).

### CODE REVIEW

**Comment by Larenall** [comment]
Manta definately needs a stats buff and better illusions. Leaving Manta and Halbert with no other items is a tree isnt the best idea so maybe its better to and them to S&Y&K tree

**Comment by Larenall** [comment]
Dont forget to secretly nerf the shit out of Heart Transplant 😉

**Comment by DarkoniusXNG** [comment]
If you ask me Hurricane Pike should not be purchasable without a core. Hurricane Pike 2 should have the recipe: `Dragon Lance 1 + Upgrade Core 1` and Hurricane Pike 1 should be unpurchasable.

Also why are you buffing Echo Sabre in the same Pull Request?

**Comment by POCKETMONEY99** [comment]
> 
> 
> If you ask me Hurricane Pike should not be purchasable without a core. Hurricane Pike 2 should have the recipe: `Dragon Lance 1 + Upgrade Core 1` and Hurricane Pike 1 should be unpurchasable.
> 
> Also why are you buffing Echo Sabre in the same Pull Request?

The reason why I made Hurricane Pike tier 1 again is because its unfair to have this item behind a core barrier. I know the idea was for the base item for X tree was supposed to be a 2k Gold Item, but that is something which has to either be implemented properly for every item tree, or done for no items. This is because it will make some items feel lacking compared to others. (For example why can I get a level 1 daedalus/Silver edge without having to be forced to commit a tier 1 core with crystalsis or shadow blade, but not be able to get a tier 1 hurricane pike.)

I buffed echo sabre because moving this item into the eye of skadi tree, it has to be comparable to eye of skadi and abyssal blade. Currently the item doesn't compare to either of these.

**Pull request closed without merging**
