### PR TITLE
Sohei

### PR DESCRIPTION
**Pull request by l34Um1**

### CODE REVIEW

**Comment by Haganeko** [comment]
The monk got night vision goggles.

**Comment by warpdragon** [comment]
He's a moon monk

**Comment by SDakFreeze** [comment]
@l34Um1 got some Sohei lore potential. 
Takuan spent most of his life helping on his parents small farm. Content to live his life on the farm, his life changed dramatically when a young 
acolyte from the monasteries of the Turstarkuri Mountains arrived. Seeking shelter, the young monk made fast friends with Takuan. Taken in by the 
young monk's story, Takuan enlisted in his kingdom's army. Showing an unnatural talent for swordplay and an unrelenting commitment to his training,
he quickly rose through the ranks. Having obtained the rank of Sohei, he beseeched his king to aid his newest friend. When the king first refused, 
the young monk then sought an audience with the king. Telling the king his tale and the danger that would eventually make its way to them, the king 
dispached a contingent of his army with the monk to track down the Dead King's army and obliteratethem. Satisfied that he could help his new friend, 
the newest Sohei took command. Side by side, they lead their forces into battle.

**Comment by Haganeko** [comment]
This is really not the place for a lore suggestion.

**Comment by SDakFreeze** [comment]
@Haganeko sorry, as I've said I'm fairly drunk and someone in Baumi's chat on twitch suggested the github and Baumi was busy with casting the tournament. This seemed like the least obstructive way to get Baumi to see it

**Pull request merged**
