### PR TITLE
Map changes

### PR DESCRIPTION
**Pull request by l34Um1**
Added additional paths to/from bosses. Reshaped the entire top and
bottom boss areas to make them be closer to the center of the map.

DO NOT IMPLEMENT THIS WITHOUT MAKING IT PRETTY FIRST.

### CODE REVIEW

**Comment by allanvbhg** [comment]
If I have time I will look at it tomorow. (Warp will probably be earlyer but ill try my best)

**Comment by Haganeko** [comment]
Screenshot, bitte.

**Comment by allanvbhg** [comment]
Whut?

**Comment by Zarnotox** [comment]
bitte means please in german (I think), I'll try to pull it on a local branch and create some

**Comment by l34Um1** [comment]
unbenannt-2
unbenannt-3
unbenannt-4
unbenannt-5
unbenannt-6
unbenannt-7

**Comment by Haganeko** [comment]
Viellen danke.

**Comment by allanvbhg** [comment]
Wait why dont the bosses spawn on the skulls?

**Comment by allanvbhg** [comment]
Or thats one of the things that needs some work

**Comment by allanvbhg** [comment]
I feel like the boxes should be moved a bunch haha. Il get on it senpai.

**Comment by warpdragon** [comment]
are you serious with this?

**Comment by warpdragon** [comment]
i'll fix it. gimme a few days I'm on vacation.

**Comment by allanvbhg** [comment]
You dont think i can do it ?

**Comment by warpdragon** [comment]
i don't want/need you to finish my work. next project maybe

**Comment by allanvbhg** [comment]
Well oke fair point haha. Il add my own touch when you finish it.

**Comment by l34Um1** [comment]
the map shouldnt look exactly like this btw. feel free to change the exact layout of the arenas and make the shape better looking and such. I mostly just wanted to showcase what I meant with "make the bosses be more accessible", so as long as that part stays feel free to mess with it as you like

**Comment by warpdragon** [comment]
I can have it ready for the weekend. Chris don't publish this yet.

**Comment by l34Um1** [comment]
already did lol

**Pull request merged**
