### PR TITLE
Balance Changes

### PR DESCRIPTION
**Pull request by DarkoniusXNG**
Objectives:

- [x] Apply 7.19c changes
~~- [ ] Nerf Spirit Breaker~~
~~- [ ] Nerf QoP Scream of Pain Fear~~

### CODE REVIEW

**Comment by chrisinajar** [comment]
don't do the other parts in this PR, separation of concerns.... this looks good to go :D

**Comment by DarkoniusXNG** [comment]
Ok, just to fix Beastmaster then and then you can merge.

**Comment by chrisinajar** [comment]
awesome, gonna do a patch in a few, lmk when you think this is ready :+1:

**Comment by DarkoniusXNG** [comment]
You can merge now if Travis check passes.

**Comment by DarkoniusXNG** [comment]
Boars don't need tooltips, wtf travis? Just merge.

**Comment by chrisinajar** [comment]
i mean... they might... can you just add it in there so travis chills?

**Comment by DarkoniusXNG** [comment]
I didn't install files for generating tooltips....

**Comment by DarkoniusXNG** [comment]
Dota already have tooltips for boars level 1 to 4, in all languages. Same thing like for lycan wolves, it was not needed.

**Comment by chrisinajar** [comment]
don't generate the tooltips, just add them to the files. Only i generate tooltips.

**Comment by chrisinajar** [comment]
use editorconfig :P

**Comment by DarkoniusXNG** [comment]
Other stuff is caused by the other PR.

**Comment by chrisinajar** [comment]
ah okay, i'll fix em at patch time then

**Pull request merged**
