### PR TITLE
Cheap armlet

### LINKED ISSUE #1215: Wrong Pricing on Armlet
It has been in the game for a while, but all the upgrades of armlet after the path of stoneskin cost 3500

### PR DESCRIPTION
**Pull request by Haganeko**
Fixes #1215.

### CODE REVIEW

**Comment by chrisinajar** [comment]
I love the item cost test cases...

**Comment by Haganeko** [comment]
I actually did the update prior to opening the PR. test case averted!

**Comment by chrisinajar** [comment]
yeah but i don't need to double check your math, since the test cases passed :+1:

**Comment by Haganeko** [comment]
True.

**Pull request merged**
