### PR TITLE
Fix Martyr's Mail Infinite Echo Damage

### LINKED ISSUE #1029: Martyr's Mail can cause infinite damage echo on self
Martyr's Mail doesn't ignore damage dealt to yourself, which can cause infinite damage instances which will either kill you or, depending on the situation, crash the game. 

How to recreate - 

* Pick a hero who can do self-damage - centaur for now.
* Max out Double Edge, get Martyr's Mail. DO NOT SKILL ANY TALENTS FOR NOW.
* Use MM followed by Double Edge. You'll be denied. Check the log, you'll find this - 

* Next, skill talents and get the +10%magic resist talent.
* MM and Double Edge again, game crashes. 

All _echoed_ damage instances of MM happen on the same server tick. If the echoed double edge kills you within a few bounces (like my screenshot), no issues, you die
If you have sufficient reduction to reduce the double edge echoed damage to less than 1 eventually, you create infinite echoes that can't kill you, in a single tick

First instance reported by _Юра Лох_ on Discord, I dug deeper.

### PR DESCRIPTION
**Pull request by Chronophylos**
I think that should fix #1029

### CODE REVIEW

**Comment by imaGecko** [comment]
does this also fix martyrs mail reflecting reflected damage?
That also causes infinite damage

**Comment by CrazyByDefault** [comment]
@imaGecko Guess not. That damage can be prevented by adding a no-reflect flag to the outgoing damage on Martyr's Mail

**Comment by Chronophylos** [comment]
I can close this PR if you want to do this (adding a no-reflect flag)

**Comment by CrazyByDefault** [comment]
Nah, I think you should do it. I'd love to contribute and I definitely plan on, but I'm still new to Lua and scripting for Dota. 

You should see more of me around, however 😄

**Comment by imaGecko** [comment]
Always in need for more lua people

**Comment by CrazyByDefault** [comment]
And the world is always in need for better custom games :D

**Comment by CrazyByDefault** [comment]
@Chronophylos Also, checked for the no-reflect flag in the docs. Seems to be missing.
image


Btw is there a separate discord/slack/gitter or something for devs? Or is it just the Minimis one?

**Comment by Trildar** [comment]
@CrazyByDefault I believe `DOTA_DAMAGE_FLAG_REFLECTION` is what we want actually. Though I'm not sure if you'd set it to true or false.
As for the Discord, there's a link somewhere in the docs for the OAA Discord.

**Comment by warpdragon** [comment]
He found it!

**Pull request merged**
