### PR TITLE
Replace Covfefe

### LINKED ISSUE #2228: Come up with a new name for Cofveve and give it a new icon
Old name is an outdated meme. Will take any suggestions.

### PR DESCRIPTION
**Pull request by warpdragon**
updated new trumps fist icon and tooltip
Tier 4
Tier 5

"Skofnung" 
"Passive: Frostburn..."
Lore: "The ancient frozen hatred within this sacred blade has the power to cease bloodflow to the extremities of its victims."
Closes #2228

### CODE REVIEW

**Comment by chrisinajar** [comment]
I am not convinced this name is better. The icon is a huge improvement.

**Comment by l34Um1** [comment]
I don't like the name. I don't know how to pronounce it.

**Comment by l34Um1** [comment]
What about Blade of Judecca? I think the icon still works just fine.

**Comment by warpdragon** [comment]
We've narrowed it down to:
Malice
Blade of Juddeca
Juddeca
Icefang
Curse of Iscariot
@l34Um1 please pick one

**Comment by chrisinajar** [comment]
i dig `Malice` or `Icefang`

**Comment by carlosrpg** [comment]
Some Sugestion:
 Blade of Agony.
 Blade of Cold Vengeance

Underlord have pit of Malice so calling it Malice could lead to confusion

**Comment by warpdragon** [comment]
> Blade of Cold Vengeance ?
skofnung

Ice Fang it is

**Comment by chrisinajar** [comment]
`Blade of Juddeca` and `Malice` are the leaders from discord conversations

**Comment by carlosrpg** [comment]
I don't like Juddeca much

**Comment by warpdragon** [comment]
i posted a vote in #general

**Comment by warpdragon** [comment]
# *Blade of Judecca!*

**Pull request merged**
