### PR TITLE
Use Lua's bit32 library

### PR DESCRIPTION
**Pull request by filalex77**

### CODE REVIEW

**Comment by Trildar** [comment]
Dota does not have `bit32`, it has `bit`, the LuaJIT BitOp library: http://bitop.luajit.org/

**Comment by filalex77** [comment]
@Trildar sure, thanks! Will patch soon.

**Comment by chrisinajar** [comment]
Yup, this is why I chose that specific implementation of sha over the others.

Is there a problem with the current hashing function that you're trying to fix? It works fine currently, confirming checksums in node.

Closing this for now since I believe it was opened under a false assumption. I'll reopen if there's something to fix here, so just let me know.. Thanks!

**Comment by filalex77** [comment]
@chrisinajar yes, just an assumption. sorry for bothering

**Pull request closed without merging**
