### PR TITLE
Update settings to allow bot AI.

### PR DESCRIPTION
**Pull request by RamonNZ**
To allow AI bots to work properly: This change must be made or bot AI won't do much at all.

I have a basic bot script which I'll add soon.

Bot requested by chrisinajar & Warpdragon.

### CODE REVIEW

**Comment by Honeth** [comment]
if they act like normal dota wouldn't that mean they buy items corresponding to their hero? if so that would make them really bad at OAA (I'm thinking in a perspective for when they substitute for a disconnected player)

**Comment by Alpha-Omega1996** [comment]
@Honeth agreed...

**Comment by Chronophylos** [comment]
We can write the Bots AI, so we decide if and what they buy. Or am I wrong?

**Comment by Honeth** [comment]
we can change what they do but i'm not sure if this value would need to be true for that would require some minor testing but i was looking at a possible future fix for disconnected players this should be fine for testing as is

**Comment by Alpha-Omega1996** [comment]
either i'm overthinking it or it is hard to write one...

**Comment by Honeth** [comment]
writing a completely new bot would certainly test your capabilities (if you want it to feel like a player) although it isn't impossible using base dota bots can work but the code itself even says in the commented part that for it to be true the game needs 3 lanes, normal items , etc. so it might be a bit buggy for OAA if we don't write our own basic bots

**Comment by Alpha-Omega1996** [comment]
as expected...........

**Comment by Haganeko** [comment]
I say we leave the ambition of substituting disconnected players for now and just make some decent bots available for testing and perhaps noobs learning the game, later.

**Comment by chrisinajar** [comment]
bots are great for testing. there's no way to spawn them without cheats on.

also most complex change eu

**Pull request merged**
