### PR TITLE
Merge MKB and Mjollnir trees

### PR DESCRIPTION
**Pull request by POCKETMONEY99**
Based on Larnells Issue #2653
 Merged MKB and Mjollnir into the same tree as these items are simillar. Also some players may wish to swap out MKB for a Mjollnir and Vice Versa depending on the amount of evasion in the game.

### CODE REVIEW

**Comment by Larenall** [comment]
To make ppl want to swap mkb for mjolnir if there isnt that much evasion, mkb needs to be nerfed and mjolnir needs to get buffed
Mjollnir
Chain Lightning dmg rescale to 200/275/350/425/500
AS to 80/95/110/125/140
1 of few AS items for carries and its not as good as it should be
MKB
Pierce dmg to 100/150/200/250/300

**Comment by POCKETMONEY99** [comment]
I have Rescaled MKB proc damage to "100 160 220 280 340". I have also increased the Static Charge damage to "200 300 400 500 600" (This is how most 200 damage nukes scale in OAA). I have also increased the damage on Chain Lightning to "170 200 325 450 575" As this would be silmillar to how a 170 damage nuke would scale in OAA (slightly less then 600 damage). The Idea behind the MKB/Mjollnir proc scaling is the level 1 MKB damage is 60% less then the level 1 Mjollnir Damage. (170*0.6=102),(575*0.6 = 345). 

I don't think I can increase the attack speed. Every time ive seen people try and increase the attack speed on this item it gets rejected. I think this is a part of the item scaling design philosophy.

**Comment by DarkoniusXNG** [comment]
MKB is the best damage item in the game and you are buffing lvl 2-4 without nerfing the bonus damage (the physical aspect of it). The scaling of bonus damage is ridiculously high. 

> The Idea behind the MKB/Mjollnir proc scaling is the level 1 MKB damage is 60% less then the level 1 Mjollnir Damage

It should be 70%. I wrote down how it should be:

MKB:
* Change bonus damage from `52 95 140 210 285` to `52 82 122 182 252`.
* Change proc damage from `100 130 185 260 370` to `100 160 220 280 340`.
* Don't change attack speed scaling.

Mjollnir:
* Change bonus damage from `24 36 56 84 120` to `24 54 94 154 224`
* Change chain proc damage from `170 200 250 350 450` to `170 270 370 470 570`.
* Don't change attack speed scaling.

**Comment by Larenall** [comment]
> MKB is the best damage item in the game and you are buffing lvl 2-4 without nerfing the bonus damage (the physical aspect of it). The scaling of bonus damage is ridiculously high.
When i suggested mkb nerf i thought about nerfing phys dmg but decided not to
Also a thing that is on my mind lately. About stat progression in oaa. Something has arithmetic type of progression and something has geometric type of progression. Isnt its more logical to have only 1?
> MKB:
> 
> * Change bonus damage from `52 95 140 210 285` to `52 82 122 182 252`.
> * Change proc damage from `100 130 185 260 370` to `100 160 220 280 340`.
Like this MKB scaling 4 example.
Most stuff has geometric so why not only have it. It makes more sense cuz of how power lvl increases throughout the game

**Comment by DarkoniusXNG** [comment]
For the stuff I wrote down I used the scaling of Deadalus as reference. I think that at the start of OAA all items scaled in a same way, but after some time some items needed a nerf or a buff. Also I think the scaling should depend on the item.

**Comment by POCKETMONEY99** [comment]
Mjonillir 
Damage "24 36 60 96 144"
Chain Damage "170 210 290 410 570"
MKB 
Damage "52 82 122 182 252"
Proc Damage "100 125 175 250 350"

I used arithmetic scaling for both items. However MKB may be too bad now in comparison to Mjollnir. There are so few viable damage items in the game that their isn't much to compare MKB to in terms of effectiveness.

**Comment by DarkoniusXNG** [comment]
https://en.wikipedia.org/wiki/Arithmetic_progression

**Comment by POCKETMONEY99** [comment]
> 
> 
> https://en.wikipedia.org/wiki/Arithmetic_progression

Ive scaled it up using some sort of pattern lol. Im not sure how you would actually write it but its previous term + [Number scaling*(Item Level -1)]

**Comment by POCKETMONEY99** [comment]
> 
> 
> https://en.wikipedia.org/wiki/Arithmetic_progression

Ive scaled it up using some sort of pattern lol. I dunno how you would actually write it but if you do previous term + [Number scaling*(Item Level -1 )

**Comment by Larenall** [comment]
What a meant for arithmetical scaling --> lvl2 item stat = lvl1 item stat + X where X is stat growth(constant). Same amount of stats every lvl

For geometrical scaling --> lvl2 item stat = lvl1 item stat + (X+Y) where X is stat growth for previopus lvl and Y is a constant. For every new lvl u gain more stats than for prev lvl. I know this isnt a geometrical scaling but idea is the same. 

My B, was tired and didnt properly explain hoping u will understand what i mean.

**Pull request merged**
