### PR TITLE
Neutral items update

### PR DESCRIPTION
**Pull request by DarkoniusXNG**
1) Max number of items per tier increased from 4 to 5.
2) Tier 1 changes:
* Removed Fairy's Trinket
3) Tier 2 changes:
* Reworked Dragon Scale - now deals 50 magic damage to the attacker every time the owner takes damage.
* Demon Stone damage penalty reduced from -100 to -30.
* Demon Stone bonus XP per minute increased from 100 to 1000.
* Demon Stone now also has attack speed penatly of -30.
* Demon Stone now has an active - summons a demon with true sight that can attack. 60s cd. 40s duration.
4) Tier 3 changes:
* Removed Craggy Coat
* Titan Sliver is now a tier 3 neutral item again.
* Reworked Creed of Omniscience - no longer gives bonus attack range and bonus attack projectile speed, now provides bonus movement speed, bonus turn rate and bonus intelligence instead.
5) Tier 4 changes:
* Tier 4 neutral items now start dropping at 30 minutes instead at 35.
* Penta-Edged Sword reworked into Blood Sword - similar stats, has an active that lets you proc your attack on any target (ally or enemy) and lifesteal from that attack. 25s cd. Cast range equal to owner's attack range. 
* Added new Tier 4 item - Rune Breaker - provides attack speed, armor, bonus dmg during duels and has an active that lets you purge buffs on enemies and break them for 4 seconds.
6) Tier 5 changes:
* Removed Pirate Hat.

### CODE REVIEW

**Comment by lovesmuffins** [comment]
Reworked Dragon Scale - now deals 50 magic damage to the attacker every time the owner takes damage....

EVERYTIME? aka intervals of .1 will kill the dude

**Comment by DarkoniusXNG** [comment]
I will put 0.5s cd.

**Comment by lovesmuffins** [comment]
> I will put 0.5s cd.

does this work with batrider napalm? Cuz even with cd this might be very stronk on batty

**Comment by DarkoniusXNG** [comment]
> does this work with batrider napalm? Cuz even with cd this might be very stronk on batty
It doesn't work with batrider napalm because this version of Dragon Scale has this flag: DOTA_DAMAGE_FLAG_REFLECTION

**Pull request merged**
