### PR TITLE
Arcane and Greater - Pips

### PR DESCRIPTION
**Pull request by hallelsegel**

### CODE REVIEW

**Comment by Trildar** [comment]
What's with `arcane_boots_1.png`?

**Comment by hallelsegel** [comment]
does it matter? its half by mistake

**Comment by imaGecko** [comment]
trildar it's correct that way

**Comment by Trildar** [comment]
Well, not really, but we don't really want extraneous files.

Gecko, I mean in `items/custom`. Not the vanilla one it `items`.

**Comment by imaGecko** [comment]
oh I didn't see that one
Yeah arcane_boots_1 doesn't belong there, or anywhere else for that matter

**Comment by hallelsegel** [comment]
right! forgot to delete it! crap

**Comment by chrisinajar** [comment]
Merge with upstream or rebase. got conflicts with your old PR

**Comment by warpdragon** [comment]
Already fixed this

**Pull request closed without merging**
