### PR TITLE
Tiny buffs

### PR DESCRIPTION
**Pull request by lovesmuffins**

### CODE REVIEW

**Comment by POCKETMONEY99** [comment]
These Changes are good.

**Comment by DarkoniusXNG** [comment]
Tiny has agility again. Pog.

**Comment by lovesmuffins** [comment]
ya having 0 agility gain in a game with 50 levels is kinda feelsbadman. So I thought I'd add some even if it isn't a lot.

**Comment by SquawkyArctangent** [comment]
If you make it 0.0205, he'll get _exactly_ 1 base agi when he hits level 50.

**Pull request closed without merging**
