### PR TITLE
Map/shop update.

### PR DESCRIPTION
**Pull request by warpdragon**
added arena shop with detection. added 1 creep camp. changed items visible in shop to include priority items. moved boss pit arena entrances.

### CODE REVIEW

**Comment by Haganeko** [comment]
Needs a second commit with the warding spots removed IIRC

**Comment by warpdragon** [comment]
Its good tho. Would like it merged. The ward spots will be fixed regardless

**Comment by chrisinajar** [comment]
includes balance changes, @Haganeko see those?

**Comment by Haganeko** [comment]
Those are mine. He just wanted to PR them. I had made a separate PR but closed it. Well, unless warp edited the file, but I trust him.

**Comment by chrisinajar** [comment]
never trust warp

**Pull request merged**
