### PR TITLE
Minimap icon png assets

### PR DESCRIPTION
**Pull request by warpdragon**

### CODE REVIEW

**Comment by warpdragon** [comment]
ok so is there some kind of git ignore on /game/materials? i keep resetting to upstream/master and my /game/materials folder still has weird shit in it.

**Comment by warpdragon** [comment]
anyway it shoudl be fine. the vmat_c stuff should compile at build time i think.

**Comment by Trildar** [comment]
All compiled files are ignored. So yeah, probably all that stuff is being ignored by git.

**Comment by Chronophylos** [comment]
what will have happened?

**Pull request merged**
