### PR TITLE
Charge BKB reworks

### LINKED ISSUE #1127: New Charge BKB upgrade ladder

### PR DESCRIPTION
**Pull request by Trildar**
Now a Lua item. Now with a more proper tooltip. Now with more sensible build path.

More importantly though, the charge mechanic has been reworked to reset like Fury Swipes, with a reset time of 10 seconds, rather than decay individually. I'm not sure if this is necessarily what we want, but Haganeko and Minna felt it was sensible enough.

Closes #1127 and #1121.

### CODE REVIEW

**Comment by JRJML** [comment]
omg did you really fix the build path?? cuz that thing was so frustrating! :blueberry:

**Comment by Haganeko** [comment]
Dummy items are missing tooltips. Had the same issue with greaves.

**Comment by Trildar** [comment]
Oh right. Those shouldn't even be purchasable in this case though (though it does appear in shop search). Guess I need tooltips anyway just to appease Travis.

**Comment by imaGecko** [comment]
The original recipe should cost 0 and include the dummy recipe in it which has the price. The dummy recipe exists just as an empty item that doesn't do anything and doesn't result in anything as you're not allowed to have 2 recipes result in the same item

**Comment by Haganeko** [comment]
The dummy recipe is purchasable - it's there in place of the actual recipe, which costs zero.

**Comment by Trildar** [comment]
Are you sure? It works in local testing. The only issue I had was that the second recipe wouldn't show build path in shop. The combining still worked. I fixed build path by making the normal recipe also have the same combination as the dummy. Means you have weirdness like BKB3 + Wand + CBKB1 Recipe + CBKB2 Recipe = CBKB2, if for some reason you buy both recipes, but that's strictly worse than the intended combination that doesn't include CBKB2 Recipe.

**Comment by imaGecko** [comment]
You could take a look at ggg

**Comment by Trildar** [comment]
I know how the GGG build path works. I'm specifically trying to do it a different way that doesn't make the Recipe tooltips look different from normal.

**Comment by Trildar** [comment]
@chrisinajar Do we want to keep enforcing the one recipe item for one result thing? What I have here seems to work fine in local testing. I can change it to be like the GGG recipes, but I don't really like that because it makes the recipe tooltips different.

**Comment by chrisinajar** [comment]
define `makes the recipe tooltips different`

**Comment by Trildar** [comment]
image
vs
image

**Comment by Haganeko** [comment]
Oh. That's a question of writing the tooltip - I was lazy and wrote it empty (also I didn't remember that recipes had tooltips)

**Comment by chrisinajar** [comment]
yeah, easily fixable. also any time you copy a tooltip exactly from dota it doesn't send it out for translations, just uses the dota ones

**Comment by Trildar** [comment]
Um. How? The recipes won't have reference to the item AbilitySpecial. Unless I suppose you want to copy that whole block to every dummy item as well. It'd be kind of annoying to have item values repeated some more whenever it comes to changing them.

**Comment by chrisinajar** [comment]
The recipe can just have the ability special values, and we can add a test case that if they exist they must be exactly equal to the item they create. Seems simple, and travis maintains it for us.

**Comment by Trildar** [comment]
Rebased and changed the recipes to pass current Travis standards. I honestly think the amount of duplication that has to be done for the tooltips is silly though. You need the KVs for cooldown, mana cost, item level, item quality, AbilitySpecial, and then you need the localisation KVs for the AbilitySpecial in the tooltip.

**Pull request merged**
