### PR TITLE
Add better XP gain on Hero Kill

### PR DESCRIPTION
**Pull request by DarkoniusXNG**
XP system is now similar to dota system with reduced values.

Change from constant _62/number of killers_ to **(20 + XPStreakBonus + 0.07*DyingHeroExperience)/number of killers**.

**XPStreakBonus** varies from 60 to 420. 60 for killing spree, 420 for beyond godlike.

Also exposed these constants in settings.lua so they can be changed more easily in the future.

### CODE REVIEW

**Comment by lovesmuffins** [comment]
Whilst I understand the complaints from "top" teams to not add it to the major, I feel like if we can test this out and see if it makes the game pace or comeback mechanic better to improve the spectator feel of oaa. We didn't do any huge changes from minor to major yet so I feel like if there's any 1 major change that should be put in it would be this. Just my cup of joe though.

**Comment by DarkoniusXNG** [comment]
Creeps XP bounties needs reducing too. That's why I think this fixed XP gain on hero kill would lead to too much experience on the map.

**Comment by lovesmuffins** [comment]
> Creeps XP bounties needs reducing too. That's why I think this fixed XP gain on hero kill would result in too much experience on the map.

You are right in that regard perhaps we should tinker with it in oaa test client

**Comment by DarkoniusXNG** [comment]
Haganeko is working on it.

**Comment by DarkoniusXNG** [comment]
This is good enough for merging.

**Pull request merged**
