### PR TITLE
Talent changes (WIP)

### PR DESCRIPTION
**Pull request by DarkoniusXNG**
Successfully changed:
* Techies +25 mines movement speed talent to +200 mines movement speed.
* AA 900 AoE Cold Feet talent to 450 AoE Cold Feet talent.

### CODE REVIEW

**Comment by l34Um1** [comment]
Hey, sorry for the late response. I agree with both changes you made but can you also try:

AM: 
lvl 20: -2.5s Blink cooldown -> -1.5s

Bounty Hunter: 
Lvl 20: +75 shuriken toss dmg -> +175
Lvl 25: +300  track gold -> +3000

Centaur:
Lvl 25: +1.5s stun duration -> +1s

Dazzle:
Lvl 10: +20 shadow wave heal/dmg -> +100
Lvl 25: +0.5 Weave armor per second -> +2.5

Doom
Lvl 15: +150 devour bonus gold -> +750

Drow Ranger:
Lvl 20: +3s gust silence duration -> 2s
Lvl 20: +20 marksmanship agility -> +40

Kotl:
Lvl 25: +200 illuminate dmg/heal -> +500

Leshrac:
Lvl 25: +50 edict explosions -> +100

Omniknight:
Lvl 25: +3s repel duration -> +2s

Queen of Pain
Lvl 25: +1.5s scream of pain fear -> +1s

Shadow Fiend
Lvl 25: -5 Precense aura armor -> -20

Spectre:
Lvl 20: +20% spectral dagger slow/bonus -> +10%

Timbersaw
Lvl 25: +8% whirling death stat loss -> +15%

Undying:
Lvl 20: +6 tombstone attacks to destory -> +4

Witch Doctor:
Lvl 25: +75 death ward damage -> +700


Ideally we would also change Io's level 25 talent to have reduced damage but I think that's a larger project.

**Comment by DarkoniusXNG** [comment]
Ok, I will start testing now. We can swap that Io talent with old talent (Tether Stuns) if you want to nerf Io. Keep that in mind.

**Comment by l34Um1** [comment]
No I don't like that change, I want to keep Io's current weirdness. Just want to make it weaker.

**Comment by DarkoniusXNG** [comment]
@l34Um1 I've changed all mentioned talents. If there is more let me know.

@chrisinajar Just a reminder if you want to merge: Travis is failing only because he/it 'thinks' that talents are items. :)

**Pull request merged**
