### PR TITLE
rename vampire tooth to vampire fang/ more tooltip cleanup

### PR DESCRIPTION
**Pull request by OTAJumperjay**
ppl have been begging for a while .. if it doesn't get merged i couldn't care less

### CODE REVIEW

**Comment by OTAJumperjay** [comment]
uuh why did it pull the stuff from my old pr that already got committed

**Comment by OTAJumperjay** [comment]
i guess it doesn't really matter since those are the same changes lul

**Comment by Haganeko** [comment]
You probably branched off your previous work branch.
That, or you had those committed to master

**Comment by Melongod** [comment]
I'm pretty sure this didn't work. I see the item as "vampire tooth".

**Comment by OTAJumperjay** [comment]
Then look again in changed files

**Comment by Chogex** [comment]
it hasn't been merged yet

**Comment by Melongod** [comment]
I know, I'm not an idiot.
I'm testing it at the moment and it hasn't worked.

**Comment by Melongod** [comment]
I'm double checking now.

**Comment by OTAJumperjay** [comment]
Itemnames are part of the tooltip file so yes

**Comment by Melongod** [comment]
Well, i ran the script to update the tooltips and it's still not working apparently.

**Comment by OTAJumperjay** [comment]
then you probably did sth wrong ... i did a lot of tooltips... had to struggle from time to time but i got this figured out by now

**Comment by imaGecko** [comment]
Changing tooltip files in itself doesn't do anything. You always need to generate a new tooltip file to actually test your changes

**Comment by carlosrpg** [comment]
Need to run the script to copy the files into addon English resource

**Comment by Melongod** [comment]
Which i did, and it didnt work ¯\_(ツ)_/¯

**Comment by Haganeko** [comment]
"Werewolves during shapeshift spawned" sounds like something Yoda would say.
"Werewolves spawned during shapeshift" is better.

**Pull request merged**
