### PR TITLE
Addon English Preliminary work

### PR DESCRIPTION
**Pull request by warpdragon**
addon_english.txt - fixed the basic physical alignment and organization of the contents of addon_english. Fixed some incorrect data.Buff Tooltips now work for Stoneskin and Lucience.
item_trumps_fists.txt - corrected the values to reflect the actual behavior of the item which i had not done correctly when i first made that KV.

### CODE REVIEW

**Comment by warpdragon** [comment]
you can just merge it.

**Comment by Declow0** [comment]
@warpdragon Why does item_trumps_fists have not any modifiers from desolator and skadi?

**Comment by chrisinajar** [comment]
If you break up your work into 2 PR's i can merge in the addon_english changes right away.

**Comment by warpdragon** [comment]
i'm not sure. here leme just...

**Comment by warpdragon** [comment]
Ok this is just the addon_english.txt

**Comment by chrisinajar** [comment]
between conflicts and new workflows, i think we close this.

**Pull request closed without merging**
