### PR TITLE
Talent buffs + Crystal Maiden and Lina Buffs

### PR DESCRIPTION
**Pull request by POCKETMONEY99**
Talent Buffs to Abaddon, Chen, Jakiro, Legion Commander, Leshrac, Tusk, Crystal Madien and Lina. Crystal Madien and Lina also got some additional buffs.

### CODE REVIEW

**Comment by DarkoniusXNG** [comment]
I need to tell you how to make these talent changes to actually work. You need to add some lines to this list: https://github.com/OpenAngelArena/oaa/blob/master/game/scripts/npc/npc_abilities_override.txt#L542-L566

**Comment by DarkoniusXNG** [comment]
For example for the abaddon talent: #base "abilities/talents/abaddon_aphotic_shield_health_talent.txt"

**Comment by lovesmuffins** [comment]
look at my invoker talent change in my balance patch

**Comment by DarkoniusXNG** [comment]
I was planning to refactor talents: to make one .txt file for each hero (for example ``abaddon_talents.txt``). So can you hold on these changes?

**Comment by POCKETMONEY99** [comment]
> 
> 
> I was planning to refactor talents: to make one .txt file for each hero (for example `abaddon_talents.txt`). So can you hold on these changes?

**Pull request closed without merging**
